# Excel Load

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
file_path = r"C:\Users\abida\OneDrive\Pictures\Banking dataset.xlsx"

excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

['accounts_deposits',
 'credit_cards',
 'loans',
 'interest_revenue',
 'defaults_credit_risk',
 'data_dictionary',
 'customers',
 'transactions',
 'product_ownership']

# Saari Tables Load

In [5]:
customers = pd.read_excel(file_path, sheet_name="customers")
loans = pd.read_excel(file_path, sheet_name="loans")
credit_cards = pd.read_excel(file_path, sheet_name="credit_cards")
defaults_credit_risk = pd.read_excel(
    r"C:\Users\abida\OneDrive\Pictures\Banking dataset.xlsx",
    sheet_name="defaults_credit_risk"
)
accounts_deposits = pd.read_excel(
    r"C:\Users\abida\OneDrive\Pictures\Banking dataset.xlsx",
    sheet_name="accounts_deposits"
)
transactions = pd.read_excel(
    r"C:\Users\abida\OneDrive\Pictures\Banking dataset.xlsx",
    sheet_name="transactions"
)
interest_revenue = pd.read_excel(
    r"C:\Users\abida\OneDrive\Pictures\Banking dataset.xlsx",
    sheet_name="interest_revenue"
)
product_ownership = pd.read_excel(
    r"C:\Users\abida\OneDrive\Pictures\Banking dataset.xlsx",
    sheet_name="product_ownership"
)

# Dataset Size

In [6]:
tables = {
    "customers": customers,
    "loans": loans,
    "credit_cards": credit_cards,
    "defaults_credit_risk": defaults_credit_risk,
    "accounts_deposits": accounts_deposits,
    "transactions": transactions,
    "interest_revenue": interest_revenue,
    "product_ownership": product_ownership
}

for name, df in tables.items():
    print(f"{name:25} {df.shape[0]:>10,} rows | {df.shape[1]:>3} columns")

customers                     10,000 rows |  10 columns
loans                          6,500 rows |  10 columns
credit_cards                   7,000 rows |   8 columns
defaults_credit_risk          10,000 rows |   7 columns
accounts_deposits             10,000 rows |   7 columns
transactions                 250,000 rows |  10 columns
interest_revenue              60,000 rows |   8 columns
product_ownership             10,000 rows |   9 columns

# First Inspection

In [7]:
for name, df in tables.items():
    print("\n" + "="*70)
    print(name.upper())
    print("="*70)
    display(df.head())

======================================================================
CUSTOMERS
======================================================================

,customer_id,customer_name,age,gender,city,occupation,education,annual_income,customer_segment,customer_since
0,CUST000001,Customer 000001,59,Female,Jaipur,Business Owner,Postgraduate,2453002,Premium,2023-08-03
1,CUST000002,Customer 000002,49,Male,Ahmedabad,Self-Employed,Graduate,2052025,Mass Market,2025-07-16
2,CUST000003,Customer 000003,35,Female,Patna,Self-Employed,Diploma,492934,Affluent,2024-06-16
3,CUST000004,Customer 000004,63,Female,Patna,Salaried,Postgraduate,482884,Mass Market,2020-07-24
4,CUST000005,Customer 000005,28,Female,Kolkata,Professional,Postgraduate,561865,Mass Market,2018-08-04

======================================================================
LOANS
======================================================================

,loan_id,customer_id,loan_type,loan_amount,outstanding_amount,interest_rate,tenure_months,start_date,loan_status,emi_amount
0,LOAN0000001,CUST007490,Home Loan,100000,42858.65,14.08,84,2022-08-01,Closed,2752.99
1,LOAN0000002,CUST006448,Home Loan,750000,594782.69,18.28,84,2024-06-19,Active,13901.01
2,LOAN0000003,CUST006486,Business Loan,1000000,842017.97,16.13,36,2019-03-19,Default,18592.35
3,LOAN0000004,CUST006221,Home Loan,500000,310144.21,12.28,240,2025-01-06,Active,10017.62
4,LOAN0000005,CUST008947,Home Loan,250000,117748.33,8.00,180,2024-10-29,Active,5654.53

======================================================================
CREDIT_CARDS
======================================================================

,card_id,customer_id,card_type,credit_limit,current_balance,utilization_pct,annual_fee,card_status
0,CARD0000001,CUST001595,Classic,50000,11030,22.06,500,Active
1,CARD0000002,CUST005607,Signature,500000,160800,32.16,5000,Active
2,CARD0000003,CUST001433,Gold,1000000,198800,19.88,1000,Active
3,CARD0000004,CUST005011,Gold,250000,84050,33.62,1000,Active
4,CARD0000005,CUST001256,Gold,100000,21010,21.01,1000,Active

======================================================================
DEFAULTS_CREDIT_RISK
======================================================================

,customer_id,credit_score,debt_to_income_pct,missed_payments_12m,delinquency_days,default_flag,risk_band
0,CUST000001,841,30.11,1,0,0,Very Low Risk
1,CUST000002,703,18.54,1,30,0,Low Risk
2,CUST000003,813,5.34,0,0,0,Very Low Risk
3,CUST000004,678,5.23,0,30,0,Low Risk
4,CUST000005,703,65.17,0,0,0,Low Risk

======================================================================
ACCOUNTS_DEPOSITS
======================================================================

,account_id,customer_id,account_type,opening_date,balance,interest_rate,account_status
0,ACC0000001,CUST000001,Current,2023-08-03,67025.63,4.32,Active
1,ACC0000002,CUST000002,Current,2025-07-16,185574.29,5.36,Active
2,ACC0000003,CUST000003,Savings,2024-06-16,23584.74,2.50,Active
3,ACC0000004,CUST000004,Savings,2020-07-24,84006.45,3.62,Active
4,ACC0000005,CUST000005,Current,2018-08-04,32166.02,7.20,Active

======================================================================
TRANSACTIONS
======================================================================

,transaction_id,customer_id,transaction_date,transaction_type,category,amount,channel,merchant,location,is_fraud
0,TXN000000001,CUST003305,2025-08-16,Credit,Fuel,1765.90,POS,Utility Provider,Jaipur,0
1,TXN000000002,CUST000103,2025-09-30,Credit,Rent,531.51,Internet Banking,Zomato,Jaipur,0
2,TXN000000003,CUST008176,2025-01-27,Debit,ATM,1221.03,Internet Banking,Swiggy,Jaipur,0
3,TXN000000004,CUST005970,2025-12-05,Credit,Groceries,2632.31,Mobile App,Uber,Kolkata,0
4,TXN000000005,CUST000580,2025-01-20,Debit,ATM,16909.86,Mobile App,Swiggy,Chennai,0

======================================================================
INTEREST_REVENUE
======================================================================

,customer_id,month,deposit_interest_expense,loan_interest_income,card_fee_income,other_fee_income,service_cost,net_revenue
0,CUST004933,2025-11-01,2800.94,7791.19,126.20,457.23,1446.52,4127.16
1,CUST002746,2025-07-01,1614.73,14421.71,424.59,210.71,1060.46,12381.82
2,CUST005412,2025-07-01,3015.63,1574.95,71.71,195.49,1846.72,-3020.20
3,CUST008614,2025-12-01,2533.28,14890.75,222.62,21.59,1769.94,10831.74
4,CUST005128,2025-07-01,3551.86,3270.01,227.82,417.97,429.84,-65.90

======================================================================
PRODUCT_OWNERSHIP
======================================================================

,customer_id,savings_account,current_account,loan,credit_card,insurance,mutual_fund,fixed_deposit,product_count
0,CUST000001,1,0,1,1,0,1,0,4
1,CUST000002,0,1,1,0,1,1,0,4
2,CUST000003,1,0,1,0,1,1,0,4
3,CUST000004,1,0,0,1,0,0,0,2
4,CUST000005,1,1,0,1,0,0,0,3

# Missing Data

In [8]:
for name, df in tables.items():
    print("\n", name)
    print(df.isnull().sum().sort_values(ascending=False).head(10))

 customers
customer_id         0
customer_name       0
age                 0
gender              0
city                0
occupation          0
education           0
annual_income       0
customer_segment    0
customer_since      0
dtype: int64

 loans
loan_id               0
customer_id           0
loan_type             0
loan_amount           0
outstanding_amount    0
interest_rate         0
tenure_months         0
start_date            0
loan_status           0
emi_amount            0
dtype: int64

 credit_cards
card_id            0
customer_id        0
card_type          0
credit_limit       0
current_balance    0
utilization_pct    0
annual_fee         0
card_status        0
dtype: int64

 defaults_credit_risk
customer_id            0
credit_score           0
debt_to_income_pct     0
missed_payments_12m    0
delinquency_days       0
default_flag           0
risk_band              0
dtype: int64

 accounts_deposits
account_id        0
customer_id       0
account_type      0
opening_date      0
balance           0
interest_rate     0
account_status    0
dtype: int64

 transactions
transaction_id      0
customer_id         0
transaction_date    0
transaction_type    0
category            0
amount              0
channel             0
merchant            0
location            0
is_fraud            0
dtype: int64

 interest_revenue
customer_id                 0
month                       0
deposit_interest_expense    0
loan_interest_income        0
card_fee_income             0
other_fee_income            0
service_cost                0
net_revenue                 0
dtype: int64

 product_ownership
customer_id        0
savings_account    0
current_account    0
loan               0
credit_card        0
insurance          0
mutual_fund        0
fixed_deposit      0
product_count      0
dtype: int64

# Duplicate Data

In [9]:
for name, df in tables.items():
    print(name, "duplicate rows:", df.duplicated().sum())

customers duplicate rows: 0
loans duplicate rows: 0
credit_cards duplicate rows: 0
defaults_credit_risk duplicate rows: 0
accounts_deposits duplicate rows: 0
transactions duplicate rows: 0
interest_revenue duplicate rows: 0
product_ownership duplicate rows: 0

# Unique Values

# Categorical columns ke liye:

In [12]:
customers["customer_segment"].value_counts(dropna=False)

customer_segment
Mass Market       5738
Affluent          2500
Premium           1336
High Net Worth     426
Name: count, dtype: int64

# Risk ke liye:

In [13]:
defaults_credit_risk["risk_band"].value_counts(dropna=False)

risk_band
Low Risk         3897
Very Low Risk    3327
Medium Risk      2487
High Risk         289
Name: count, dtype: int64

# Numerical Statistics

In [14]:
for name, df in tables.items():
    print("\n", name)
    display(df.describe().T)

 customers

,count,mean,min,25%,50%,75%,max,std
age,10000.0,45.6204,21.0,33.0,46.0,58.0,70.0,14.343489
annual_income,10000.0,813299.7559,150000.0,425152.5,656077.0,1013473.5,7566840.0,589508.359628
customer_since,10000,2021-01-10 17:03:24.480000,2016-01-01 00:00:00,2018-07-07 18:00:00,2021-01-17 00:00:00,2023-07-18 00:00:00,2025-12-28 00:00:00,NaN

 loans

,count,mean,min,25%,50%,75%,max,std
loan_amount,6500.0,1474338.461538,100000.0,500000.0,1000000.0,2500000.0,5000000.0,1546026.164187
outstanding_amount,6500.0,745314.708151,5013.2,131178.9725,381899.01,900631.955,4747812.92,964365.441701
interest_rate,6500.0,12.854365,7.0,9.97,12.89,15.76,18.5,3.321789
tenure_months,6500.0,88.932923,12.0,36.0,60.0,120.0,240.0,71.737883
start_date,6500,2022-07-11 08:46:49.107692032,2019-01-01 00:00:00,2020-09-23 18:00:00,2022-07-02 00:00:00,2024-04-25 00:00:00,2026-02-12 00:00:00,NaN
emi_amount,6500.0,39017.613402,1802.15,9045.245,23099.01,50259.86,174896.81,42075.829368

 credit_cards

,count,mean,std,min,25%,50%,75%,max
credit_limit,7000.0,349792.857143,329827.007795,50000.00,100000.000,250000.00,500000.00,1000000.00
current_balance,7000.0,99355.609286,119695.184300,360.00,21823.750,50325.00,130587.50,797500.00
utilization_pct,7000.0,28.383139,15.802484,0.24,16.065,26.15,38.79,84.75
annual_fee,7000.0,1454.071429,1296.763309,500.00,500.000,1000.00,2500.00,5000.00

 defaults_credit_risk

,count,mean,std,min,25%,50%,75%,max
credit_score,10000.0,709.131900,67.750933,456.0,663.00,709.00,757.00,850.00
debt_to_income_pct,10000.0,38.015052,17.590472,2.0,25.62,37.81,50.19,113.14
missed_payments_12m,10000.0,0.715400,0.836225,0.0,0.00,1.00,1.00,5.00
delinquency_days,10000.0,24.587000,30.996863,0.0,0.00,15.00,30.00,90.00
default_flag,10000.0,0.150000,0.357089,0.0,0.00,0.00,0.00,1.00

 accounts_deposits

,count,mean,min,25%,50%,75%,max,std
opening_date,10000,2021-01-10 17:03:24.480000,2016-01-01 00:00:00,2018-07-07 18:00:00,2021-01-17 00:00:00,2023-07-18 00:00:00,2025-12-28 00:00:00,NaN
balance,10000.0,138076.450612,1653.08,43382.2075,84584.33,164131.2575,3651183.01,176776.044761
interest_rate,10000.0,4.871517,2.5,3.68,4.89,6.05,7.25,1.370043

 transactions

,count,mean,min,25%,50%,75%,max,std
transaction_date,250000,2025-07-01 23:53:39.148800,2025-01-01 00:00:00,2025-04-02 00:00:00,2025-07-02 00:00:00,2025-10-01 00:00:00,2025-12-31 00:00:00,NaN
amount,250000.0,3609.79916,22.18,1114.48,2191.31,4301.9975,222480.91,4693.077714
is_fraud,250000.0,0.00672,0.0,0.0,0.0,0.0,1.0,0.0817

 interest_revenue

,count,mean,min,25%,50%,75%,max,std
month,60000,2025-06-17 01:12:41.760000,2025-01-01 00:00:00,2025-04-01 00:00:00,2025-07-01 00:00:00,2025-10-01 00:00:00,2025-12-01 00:00:00,NaN
deposit_interest_expense,60000.0,2110.41388,200.03,1161.0475,2115.12,3057.89,3999.93,1096.215152
loan_interest_income,60000.0,7480.444531,0.41,3754.69,7445.24,11216.475,14999.99,4328.192631
card_fee_income,60000.0,249.876445,0.0,124.15,249.955,375.775,500.0,144.486093
other_fee_income,60000.0,401.12043,0.0,203.465,400.44,600.81,799.99,230.336497
service_cost,60000.0,2524.728621,50.14,1272.1525,2536.57,3767.3025,4999.76,1434.964574
net_revenue,60000.0,3496.298906,-8412.59,-245.915,3468.475,7233.1425,15290.77,4683.683742

 product_ownership

                   count    mean       std  min  25%  50%  75%  max
savings_account  10000.0  0.9493  0.219395  0.0  1.0  1.0  1.0  1.0
current_account  10000.0  0.2496  0.432803  0.0  0.0  0.0  0.0  1.0
loan             10000.0  0.5509  0.497427  0.0  0.0  1.0  1.0  1.0
credit_card      10000.0  0.6897  0.462640  0.0  0.0  1.0  1.0  1.0
insurance        10000.0  0.3533  0.478019  0.0  0.0  0.0  1.0  1.0
mutual_fund      10000.0  0.2777  0.447887  0.0  0.0  0.0  1.0  1.0
fixed_deposit    10000.0  0.2964  0.456692  0.0  0.0  0.0  1.0  1.0
product_count    10000.0  3.3669  1.159146  0.0  3.0  3.0  4.0  7.0

# Missing Value Analysis

In [15]:
missing_report = []

for name, df in tables.items():

    total_rows = len(df)

    for column in df.columns:

        missing_count = df[column].isna().sum()

        missing_report.append({
            "table": name,
            "column": column,
            "missing_count": missing_count,
            "missing_pct": round(
                (missing_count / total_rows) * 100, 2
            )
        })

missing_report = pd.DataFrame(missing_report)

missing_report = missing_report.sort_values(
    "missing_pct",
    ascending=False
)

missing_report.head(30)

                table                    column  missing_count  missing_pct
0           customers               customer_id              0          0.0
44       transactions          transaction_date              0          0.0
50       transactions                  location              0          0.0
49       transactions                  merchant              0          0.0
48       transactions                   channel              0          0.0
47       transactions                    amount              0          0.0
46       transactions                  category              0          0.0
45       transactions          transaction_type              0          0.0
43       transactions               customer_id              0          0.0
35  accounts_deposits                account_id              0          0.0
42       transactions            transaction_id              0          0.0
41  accounts_deposits            account_status              0          0.0
40  accounts_deposits             interest_rate              0          0.0
39  accounts_deposits                   balance              0          0.0
38  accounts_deposits              opening_date              0          0.0
37  accounts_deposits              account_type              0          0.0
51       transactions                  is_fraud              0          0.0
52   interest_revenue               customer_id              0          0.0
53   interest_revenue                     month              0          0.0
54   interest_revenue  deposit_interest_expense              0          0.0
55   interest_revenue      loan_interest_income              0          0.0
56   interest_revenue           card_fee_income              0          0.0
57   interest_revenue          other_fee_income              0          0.0
58   interest_revenue              service_cost              0          0.0
59   interest_revenue               net_revenue              0          0.0
60  product_ownership               customer_id              0          0.0
61  product_ownership           savings_account              0          0.0
62  product_ownership           current_account              0          0.0
63  product_ownership                      loan              0          0.0
64  product_ownership               credit_card              0          0.0

# Duplicate Analysis

In [16]:
for name, df in tables.items():

    duplicate_count = df.duplicated().sum()

    print(
        f"{name}: "
        f"{duplicate_count:,} duplicate rows"
    )

customers: 0 duplicate rows
loans: 0 duplicate rows
credit_cards: 0 duplicate rows
defaults_credit_risk: 0 duplicate rows
accounts_deposits: 0 duplicate rows
transactions: 0 duplicate rows
interest_revenue: 0 duplicate rows
product_ownership: 0 duplicate rows

# Customer ID Validation

In [17]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [18]:
duplicate_customers = customers[
    customers["customer_id"].duplicated(
        keep=False
    )
].sort_values("customer_id")

duplicate_customers

Empty DataFrame
Columns: [customer_id, customer_name, age, gender, city, occupation, education, annual_income, customer_segment, customer_since]
Index: []

# Other Key Validation
Loans

In [19]:
loans["loan_id"].duplicated().sum()

np.int64(0)

 #
 Credit Cards

In [22]:
credit_cards["card_id"].duplicated().sum()

np.int64(0)

# 
Transactions

In [23]:
transactions["transaction_id"].duplicated().sum()

np.int64(0)

#
Risk table

In [24]:
defaults_credit_risk["customer_id"].duplicated().sum()

np.int64(0)

# Data Type Validation

In [25]:
for name, df in tables.items():

    print("\n" + "="*60)
    print(name.upper())
    print("="*60)

    print(df.dtypes)

============================================================
CUSTOMERS
============================================================
customer_id                 object
customer_name               object
age                          int64
gender                      object
city                        object
occupation                  object
education                   object
annual_income                int64
customer_segment            object
customer_since      datetime64[ns]
dtype: object

============================================================
LOANS
============================================================
loan_id                       object
customer_id                   object
loan_type                     object
loan_amount                    int64
outstanding_amount           float64
interest_rate                float64
tenure_months                  int64
start_date            datetime64[ns]
loan_status                   object
emi_amount                   float64
dtype: object

============================================================
CREDIT_CARDS
============================================================
card_id             object
customer_id         object
card_type           object
credit_limit         int64
current_balance      int64
utilization_pct    float64
annual_fee           int64
card_status         object
dtype: object

============================================================
DEFAULTS_CREDIT_RISK
============================================================
customer_id             object
credit_score             int64
debt_to_income_pct     float64
missed_payments_12m      int64
delinquency_days         int64
default_flag             int64
risk_band               object
dtype: object

============================================================
ACCOUNTS_DEPOSITS
============================================================
account_id                object
customer_id               object
account_type              object
opening_date      datetime64[ns]
balance                  float64
interest_rate            float64
account_status            object
dtype: object

============================================================
TRANSACTIONS
============================================================
transaction_id              object
customer_id                 object
transaction_date    datetime64[ns]
transaction_type            object
category                    object
amount                     float64
channel                     object
merchant                    object
location                    object
is_fraud                     int64
dtype: object

============================================================
INTEREST_REVENUE
============================================================
customer_id                         object
month                       datetime64[ns]
deposit_interest_expense           float64
loan_interest_income               float64
card_fee_income                    float64
other_fee_income                   float64
service_cost                       float64
net_revenue                        float64
dtype: object

============================================================
PRODUCT_OWNERSHIP
============================================================
customer_id        object
savings_account     int64
current_account     int64
loan                int64
credit_card         int64
insurance           int64
mutual_fund         int64
fixed_deposit       int64
product_count       int64
dtype: object

# Dates

In [26]:
customers["customer_since"] = pd.to_datetime(
    customers["customer_since"],
    errors="coerce"
)

# Numeric Validity Checks

# Age

In [27]:
customers[
    (customers["age"] < 18) |
    (customers["age"] > 100)
]

Empty DataFrame
Columns: [customer_id, customer_name, age, gender, city, occupation, education, annual_income, customer_segment, customer_since]
Index: []

# Annual Income

In [28]:
customers[
    customers["annual_income"] < 0
]

Empty DataFrame
Columns: [customer_id, customer_name, age, gender, city, occupation, education, annual_income, customer_segment, customer_since]
Index: []

# Credit Score

In [30]:
defaults_credit_risk[
    (defaults_credit_risk["credit_score"] < 300) |
    (defaults_credit_risk["credit_score"] > 850)
]

Empty DataFrame
Columns: [customer_id, credit_score, debt_to_income_pct, missed_payments_12m, delinquency_days, default_flag, risk_band]
Index: []

# DTI

In [31]:
defaults_credit_risk[
    defaults_credit_risk["debt_to_income_pct"] < 0
]

Empty DataFrame
Columns: [customer_id, credit_score, debt_to_income_pct, missed_payments_12m, delinquency_days, default_flag, risk_band]
Index: []

# Utilization

In [32]:
credit_cards[
    credit_cards["utilization_pct"] < 0
]

Empty DataFrame
Columns: [card_id, customer_id, card_type, credit_limit, current_balance, utilization_pct, annual_fee, card_status]
Index: []

In [33]:
credit_cards[
    credit_cards["utilization_pct"] > 100
]

Empty DataFrame
Columns: [card_id, customer_id, card_type, credit_limit, current_balance, utilization_pct, annual_fee, card_status]
Index: []

# Loan Validation

In [34]:
loans[
    loans["loan_amount"] <= 0
]

Empty DataFrame
Columns: [loan_id, customer_id, loan_type, loan_amount, outstanding_amount, interest_rate, tenure_months, start_date, loan_status, emi_amount]
Index: []

# Outstanding amount:

In [35]:
loans[
    loans["outstanding_amount"] < 0
]

Empty DataFrame
Columns: [loan_id, customer_id, loan_type, loan_amount, outstanding_amount, interest_rate, tenure_months, start_date, loan_status, emi_amount]
Index: []

# Aur important:

In [36]:
loans[
    loans["outstanding_amount"] >
    loans["loan_amount"]
]

Empty DataFrame
Columns: [loan_id, customer_id, loan_type, loan_amount, outstanding_amount, interest_rate, tenure_months, start_date, loan_status, emi_amount]
Index: []

# Categorical Standardization

In [37]:
customers["gender"].value_counts(dropna=False)

gender
Male      5496
Female    4409
Other       95
Name: count, dtype: int64

In [38]:
customers["customer_segment"].value_counts(dropna=False)

customer_segment
Mass Market       5738
Affluent          2500
Premium           1336
High Net Worth     426
Name: count, dtype: int64

In [39]:
loans["loan_type"].value_counts(dropna=False)

loan_type
Personal Loan     2014
Home Loan         1573
Auto Loan         1167
Business Loan     1121
Education Loan     625
Name: count, dtype: int64

# Agar inconsistency hai to standardize:

In [40]:
customers["gender"] = (
    customers["gender"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Relationship Validation

In [41]:
customer_ids = set(customers["customer_id"])

orphan_loans = loans[
    ~loans["customer_id"].isin(customer_ids)
]

len(orphan_loans)

0

In [42]:
orphan_risk = defaults_credit_risk[
    ~defaults_credit_risk["customer_id"].isin(customer_ids)
]

len(orphan_risk)

0

# Create Clean Data Copies

In [43]:
customers_clean = customers.copy()
loans_clean = loans.copy()
credit_cards_clean = credit_cards.copy()
defaults_credit_risk_clean = defaults_credit_risk.copy()
accounts_deposits_clean = accounts_deposits.copy()
transactions_clean = transactions.copy()
interest_revenue_clean = interest_revenue.copy()
product_ownership_clean = product_ownership.copy()

# Credit Risk Feature Engineering

#
Customer Financial Profile

#
Annual Income Band

In [44]:
def income_band(income):
    if income < 300000:
        return "Low Income"
    elif income < 600000:
        return "Lower Middle Income"
    elif income < 1200000:
        return "Middle Income"
    elif income < 2500000:
        return "Upper Middle Income"
    else:
        return "High Income"

customers_clean["income_band"] = (
    customers_clean["annual_income"]
    .apply(income_band)
)

# Age Segmentation

In [45]:
def age_group(age):
    if age < 25:
        return "18-24"
    elif age < 35:
        return "25-34"
    elif age < 45:
        return "35-44"
    elif age < 55:
        return "45-54"
    elif age < 65:
        return "55-64"
    else:
        return "65+"

customers_clean["age_group"] = (
    customers_clean["age"]
    .apply(age_group)
)

# DTI — Debt Burden

In [46]:
def dti_band(dti):
    if dti < 20:
        return "Low DTI"
    elif dti < 40:
        return "Moderate DTI"
    elif dti < 60:
        return "High DTI"
    else:
        return "Very High DTI"

defaults_credit_risk_clean["dti_band"] = (
    defaults_credit_risk_clean["debt_to_income_pct"]
    .apply(dti_band)
)

# Credit Score Band

In [47]:
def credit_score_band(score):
    if score < 580:
        return "Poor"
    elif score < 670:
        return "Fair"
    elif score < 740:
        return "Good"
    elif score < 800:
        return "Very Good"
    else:
        return "Exceptional"

defaults_credit_risk_clean["credit_score_band"] = (
    defaults_credit_risk_clean["credit_score"]
    .apply(credit_score_band)
)

# Payment Stress

# Missed Payment Band

In [48]:
def missed_payment_band(x):
    if x == 0:
        return "No Missed Payment"
    elif x == 1:
        return "1 Missed Payment"
    elif x <= 3:
        return "2-3 Missed Payments"
    else:
        return "4+ Missed Payments"

defaults_credit_risk_clean["missed_payment_band"] = (
    defaults_credit_risk_clean["missed_payments_12m"]
    .apply(missed_payment_band)
)

# Delinquency Band

In [49]:
def delinquency_band(days):
    if days == 0:
        return "No Delinquency"
    elif days <= 30:
        return "1-30 Days"
    elif days <= 60:
        return "31-60 Days"
    elif days <= 90:
        return "61-90 Days"
    else:
        return "90+ Days"

defaults_credit_risk_clean["delinquency_band"] = (
    defaults_credit_risk_clean["delinquency_days"]
    .apply(delinquency_band)
)

# Credit Card Utilization

In [50]:
def utilization_band(x):
    if x < 30:
        return "Low Utilization"
    elif x < 50:
        return "Moderate Utilization"
    elif x < 75:
        return "High Utilization"
    else:
        return "Very High Utilization"

credit_cards_clean["utilization_band"] = (
    credit_cards_clean["utilization_pct"]
    .apply(utilization_band)
)

# Loan Exposure

In [51]:
loans_clean["outstanding_ratio"] = (
    loans_clean["outstanding_amount"]
    / loans_clean["loan_amount"]
) * 100

# Loan Exposure Band

In [52]:
def exposure_band(x):
    if x < 100000:
        return "Low Exposure"
    elif x < 500000:
        return "Medium Exposure"
    elif x < 1000000:
        return "High Exposure"
    else:
        return "Very High Exposure"

loans_clean["exposure_band"] = (
    loans_clean["outstanding_amount"]
    .apply(exposure_band)
)

# Customer Loan Exposure

In [53]:
customer_loan_summary = (
    loans_clean
    .groupby("customer_id")
    .agg(
        total_loans=("loan_id", "nunique"),
        total_loan_amount=("loan_amount", "sum"),
        total_outstanding=("outstanding_amount", "sum"),
        avg_interest_rate=("interest_rate", "mean")
    )
    .reset_index()
)

# Credit Card Exposure

In [54]:
customer_card_summary = (
    credit_cards_clean
    .groupby("customer_id")
    .agg(
        total_cards=("card_id", "nunique"),
        total_credit_limit=("credit_limit", "sum"),
        total_card_balance=("current_balance", "sum"),
        avg_utilization=("utilization_pct", "mean")
    )
    .reset_index()
)

# Transaction Behaviour

In [55]:
customer_transaction_summary = (
    transactions_clean
    .groupby("customer_id")
    .agg(
        total_transactions=("transaction_id", "count"),
        total_transaction_amount=("amount", "sum"),
        avg_transaction_amount=("amount", "mean")
    )
    .reset_index()
)

# Revenue / Customer Value

In [58]:
customer_revenue_summary = (
    interest_revenue_clean
    .groupby("customer_id")
    .agg(
        total_revenue=("net_revenue", "sum")
    )
    .reset_index()
)

customer_revenue_summary.head()

  customer_id  total_revenue
0  CUST000001        6757.69
1  CUST000002       -6888.28
2  CUST000003       13831.55
3  CUST000004        3800.41
4  CUST000005       27284.57

# Check

In [59]:
customer_revenue_summary.shape

(9977, 2)

In [60]:
customer_revenue_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9977 entries, 0 to 9976
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    9977 non-null   object
 1   total_revenue  9977 non-null   float64
dtypes: float64(1), object(1)
memory usage: 156.0+ KB

In [61]:
customer_revenue_summary = (
    interest_revenue_clean
    .groupby("customer_id")
    .agg(
        total_loan_interest_income=("loan_interest_income", "sum"),
        total_card_fee_income=("card_fee_income", "sum"),
        total_other_fee_income=("other_fee_income", "sum"),
        total_deposit_interest_expense=("deposit_interest_expense", "sum"),
        total_service_cost=("service_cost", "sum"),
        total_net_revenue=("net_revenue", "sum")
    )
    .reset_index()
)

customer_revenue_summary.head()

,customer_id,total_loan_interest_income,total_card_fee_income,total_other_fee_income,total_deposit_interest_expense,total_service_cost,total_net_revenue
0,CUST000001,20586.21,334.29,1106.97,6565.27,8704.51,6757.69
1,CUST000002,31340.02,1994.14,2316.11,18462.30,24076.25,-6888.28
2,CUST000003,31517.21,1014.97,1940.90,7170.60,13470.93,13831.55
3,CUST000004,14974.13,866.11,856.17,6856.85,6039.15,3800.41
4,CUST000005,46828.19,2055.05,2788.02,11606.03,12780.66,27284.57

# Customer Loan Summary

In [63]:
customer_loan_summary = (
    loans_clean
    .groupby("customer_id")
    .agg(
        total_loans=("loan_id", "nunique"),
        total_loan_amount=("loan_amount", "sum"),
        total_outstanding=("outstanding_amount", "sum"),
        avg_interest_rate=("interest_rate", "mean")
    )
    .reset_index()
)

customer_loan_summary.head()

,customer_id,total_loans,total_loan_amount,total_outstanding,avg_interest_rate
0,CUST000001,1,750000,408017.88,8.290000
1,CUST000006,3,5250000,2171614.29,14.986667
2,CUST000008,2,3000000,873601.98,11.965000
3,CUST000010,1,750000,209030.16,10.760000
4,CUST000011,1,1000000,944715.05,14.460000

# Customer Card Summary

In [64]:
customer_card_summary = (
    credit_cards_clean
    .groupby("customer_id")
    .agg(
        total_cards=("card_id", "nunique"),
        total_credit_limit=("credit_limit", "sum"),
        total_card_balance=("current_balance", "sum"),
        avg_utilization=("utilization_pct", "mean")
    )
    .reset_index()
)

customer_card_summary.head()

,customer_id,total_cards,total_credit_limit,total_card_balance,avg_utilization
0,CUST000001,1,500000,214600,42.920
1,CUST000002,2,600000,100720,22.680
2,CUST000004,2,1050000,95940,15.475
3,CUST000006,1,50000,13475,26.950
4,CUST000007,1,50000,1680,3.360

# Customer Product Summary — corrected for your dataset

In [65]:
customer_product_summary = (
    product_ownership_clean
    [
        [
            "customer_id",
            "savings_account",
            "current_account",
            "loan",
            "credit_card",
            "insurance",
            "mutual_fund",
            "fixed_deposit",
            "product_count"
        ]
    ]
    .copy()
)

customer_product_summary.head()

,customer_id,savings_account,current_account,loan,credit_card,insurance,mutual_fund,fixed_deposit,product_count
0,CUST000001,1,0,1,1,0,1,0,4
1,CUST000002,0,1,1,0,1,1,0,4
2,CUST000003,1,0,1,0,1,1,0,4
3,CUST000004,1,0,0,1,0,0,0,2
4,CUST000005,1,1,0,1,0,0,0,3

# Customer Transaction Summary

In [66]:
customer_transaction_summary = (
    transactions_clean
    .groupby("customer_id")
    .agg(
        total_transactions=("transaction_id", "nunique"),
        total_transaction_amount=("amount", "sum"),
        avg_transaction_amount=("amount", "mean")
    )
    .reset_index()
)

customer_transaction_summary.head()

,customer_id,total_transactions,total_transaction_amount,avg_transaction_amount
0,CUST000001,20,69032.27,3451.613500
1,CUST000002,29,76901.26,2651.767586
2,CUST000003,28,109221.74,3900.776429
3,CUST000004,27,122200.65,4525.950000
4,CUST000005,29,79254.54,2732.915172

# Customer Revenue Summary — using your actual columns

In [67]:
customer_revenue_summary = (
    interest_revenue_clean
    .groupby("customer_id")
    .agg(
        total_loan_interest_income=("loan_interest_income", "sum"),
        total_card_fee_income=("card_fee_income", "sum"),
        total_other_fee_income=("other_fee_income", "sum"),
        total_deposit_interest_expense=("deposit_interest_expense", "sum"),
        total_service_cost=("service_cost", "sum"),
        total_net_revenue=("net_revenue", "sum")
    )
    .reset_index()
)

customer_revenue_summary.head()

,customer_id,total_loan_interest_income,total_card_fee_income,total_other_fee_income,total_deposit_interest_expense,total_service_cost,total_net_revenue
0,CUST000001,20586.21,334.29,1106.97,6565.27,8704.51,6757.69
1,CUST000002,31340.02,1994.14,2316.11,18462.30,24076.25,-6888.28
2,CUST000003,31517.21,1014.97,1940.90,7170.60,13470.93,13831.55
3,CUST000004,14974.13,866.11,856.17,6856.85,6039.15,3800.41
4,CUST000005,46828.19,2055.05,2788.02,11606.03,12780.66,27284.57

# Now create customer_360

In [68]:
customer_360 = (
    customers_clean
    .merge(
        defaults_credit_risk_clean,
        on="customer_id",
        how="left"
    )
    .merge(
        customer_loan_summary,
        on="customer_id",
        how="left"
    )
    .merge(
        customer_card_summary,
        on="customer_id",
        how="left"
    )
    .merge(
        customer_product_summary,
        on="customer_id",
        how="left"
    )
    .merge(
        customer_transaction_summary,
        on="customer_id",
        how="left"
    )
    .merge(
        customer_revenue_summary,
        on="customer_id",
        how="left"
    )
)

customer_360.head()

,customer_id,customer_name,age,gender,city,occupation,education,annual_income,customer_segment,customer_since,income_band,age_group,credit_score,debt_to_income_pct,missed_payments_12m,delinquency_days,default_flag,risk_band,dti_band,credit_score_band,missed_payment_band,delinquency_band,total_loans,total_loan_amount,total_outstanding,avg_interest_rate,total_cards,total_credit_limit,total_card_balance,avg_utilization,savings_account,current_account,loan,credit_card,insurance,mutual_fund,fixed_deposit,product_count,total_transactions,total_transaction_amount,avg_transaction_amount,total_loan_interest_income,total_card_fee_income,total_other_fee_income,total_deposit_interest_expense,total_service_cost,total_net_revenue
0,CUST000001,Customer 000001,59,Female,Jaipur,Business Owner,Postgraduate,2453002,Premium,2023-08-03,Upper Middle Income,55-64,841,30.11,1,0,0,Very Low Risk,Moderate DTI,Exceptional,1 Missed Payment,No Delinquency,1.0,750000.0,408017.88,8.29,1.0,500000.0,214600.0,42.920,1,0,1,1,0,1,0,4,20,69032.27,3451.613500,20586.21,334.29,1106.97,6565.27,8704.51,6757.69
1,CUST000002,Customer 000002,49,Male,Ahmedabad,Self-Employed,Graduate,2052025,Mass Market,2025-07-16,Upper Middle Income,45-54,703,18.54,1,30,0,Low Risk,Low DTI,Good,1 Missed Payment,1-30 Days,NaN,NaN,NaN,NaN,2.0,600000.0,100720.0,22.680,0,1,1,0,1,1,0,4,29,76901.26,2651.767586,31340.02,1994.14,2316.11,18462.30,24076.25,-6888.28
2,CUST000003,Customer 000003,35,Female,Patna,Self-Employed,Diploma,492934,Affluent,2024-06-16,Lower Middle Income,35-44,813,5.34,0,0,0,Very Low Risk,Low DTI,Exceptional,No Missed Payment,No Delinquency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,1,0,4,28,109221.74,3900.776429,31517.21,1014.97,1940.90,7170.60,13470.93,13831.55
3,CUST000004,Customer 000004,63,Female,Patna,Salaried,Postgraduate,482884,Mass Market,2020-07-24,Lower Middle Income,55-64,678,5.23,0,30,0,Low Risk,Low DTI,Good,No Missed Payment,1-30 Days,NaN,NaN,NaN,NaN,2.0,1050000.0,95940.0,15.475,1,0,0,1,0,0,0,2,27,122200.65,4525.950000,14974.13,866.11,856.17,6856.85,6039.15,3800.41
4,CUST000005,Customer 000005,28,Female,Kolkata,Professional,Postgraduate,561865,Mass Market,2018-08-04,Lower Middle Income,25-34,703,65.17,0,0,0,Low Risk,Very High DTI,Good,No Missed Payment,No Delinquency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,1,0,0,0,3,29,79254.54,2732.915172,46828.19,2055.05,2788.02,11606.03,12780.66,27284.57

# Immediately verify it

In [69]:
print("Rows:", customer_360.shape[0])
print("Columns:", customer_360.shape[1])

customer_360.info()

Rows: 10000
Columns: 47
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   customer_id                     10000 non-null  object
 1   customer_name                   10000 non-null  object
 2   age                             10000 non-null  int64
 3   gender                          10000 non-null  string
 4   city                            10000 non-null  object
 5   occupation                      10000 non-null  object
 6   education                       10000 non-null  object
 7   annual_income                   10000 non-null  int64
 8   customer_segment                10000 non-null  object
 9   customer_since                  10000 non-null  datetime64[ns]
 10  income_band                     10000 non-null  object
 11  age_group                       10000 non-null  object
 12  credit_score                    10000 non-null  int64
 13  debt_to_income_pct              10000 non-null  float64
 14  missed_payments_12m             10000 non-null  int64
 15  delinquency_days                10000 non-null  int64
 16  default_flag                    10000 non-null  int64
 17  risk_band                       10000 non-null  object
 18  dti_band                        10000 non-null  object
 19  credit_score_band               10000 non-null  object
 20  missed_payment_band             10000 non-null  object
 21  delinquency_band                10000 non-null  object
 22  total_loans                     4818 non-null   float64
 23  total_loan_amount               4818 non-null   float64
 24  total_outstanding               4818 non-null   float64
 25  avg_interest_rate               4818 non-null   float64
 26  total_cards                     5057 non-null   float64
 27  total_credit_limit              5057 non-null   float64
 28  total_card_balance              5057 non-null   float64
 29  avg_utilization                 5057 non-null   float64
 30  savings_account                 10000 non-null  int64
 31  current_account                 10000 non-null  int64
 32  loan                            10000 non-null  int64
 33  credit_card                     10000 non-null  int64
 34  insurance                       10000 non-null  int64
 35  mutual_fund                     10000 non-null  int64
 36  fixed_deposit                   10000 non-null  int64
 37  product_count                   10000 non-null  int64
 38  total_transactions              10000 non-null  int64
 39  total_transaction_amount        10000 non-null  float64
 40  avg_transaction_amount          10000 non-null  float64
 41  total_loan_interest_income      9977 non-null   float64
 42  total_card_fee_income           9977 non-null   float64
 43  total_other_fee_income          9977 non-null   float64
 44  total_deposit_interest_expense  9977 non-null   float64
 45  total_service_cost              9977 non-null   float64
 46  total_net_revenue               9977 non-null   float64
dtypes: datetime64[ns](1), float64(17), int64(15), object(13), string(1)
memory usage: 3.6+ MB

In [70]:
customer_360.isna().sum().sort_values(ascending=False).head(20)

total_loan_amount                 5182
total_loans                       5182
avg_interest_rate                 5182
total_outstanding                 5182
avg_utilization                   4943
total_card_balance                4943
total_credit_limit                4943
total_cards                       4943
total_service_cost                  23
total_deposit_interest_expense      23
total_other_fee_income              23
total_card_fee_income               23
total_loan_interest_income          23
total_net_revenue                   23
missed_payments_12m                  0
current_account                      0
age                                  0
gender                               0
city                                 0
occupation                           0
dtype: int64

# Most important check: one row per customer

In [71]:
duplicate_customers = customer_360["customer_id"].duplicated().sum()

print("Duplicate customer IDs:", duplicate_customers)

Duplicate customer IDs: 0

In [72]:
print("Unique customers:", customer_360["customer_id"].nunique())
print("Total rows:", len(customer_360))

Unique customers: 10000
Total rows: 10000

In [74]:
customer_product_summary

,customer_id,savings_account,current_account,loan,credit_card,insurance,mutual_fund,fixed_deposit,product_count
0,CUST000001,1,0,1,1,0,1,0,4
1,CUST000002,0,1,1,0,1,1,0,4
2,CUST000003,1,0,1,0,1,1,0,4
3,CUST000004,1,0,0,1,0,0,0,2
4,CUST000005,1,1,0,1,0,0,0,3
...,...,...,...,...,...,...,...,...,...
9995,CUST009996,1,1,1,1,0,0,0,4
9996,CUST009997,1,0,1,0,1,0,0,3
9997,CUST009998,1,0,1,0,1,0,0,3
9998,CUST009999,1,0,1,1,0,0,0,3
9999,CUST010000,1,0,0,1,1,0,0,3

In [75]:
customer_360.shape
customer_360["customer_id"].nunique()
customer_360["customer_id"].duplicated().sum()

np.int64(0)

# Overall Credit Risk Baseline

#
Check the default column

In [77]:
customer_360.columns.tolist()

['customer_id',
 'customer_name',
 'age',
 'gender',
 'city',
 'occupation',
 'education',
 'annual_income',
 'customer_segment',
 'customer_since',
 'income_band',
 'age_group',
 'credit_score',
 'debt_to_income_pct',
 'missed_payments_12m',
 'delinquency_days',
 'default_flag',
 'risk_band',
 'dti_band',
 'credit_score_band',
 'missed_payment_band',
 'delinquency_band',
 'total_loans',
 'total_loan_amount',
 'total_outstanding',
 'avg_interest_rate',
 'total_cards',
 'total_credit_limit',
 'total_card_balance',
 'avg_utilization',
 'savings_account',
 'current_account',
 'loan',
 'credit_card',
 'insurance',
 'mutual_fund',
 'fixed_deposit',
 'product_count',
 'total_transactions',
 'total_transaction_amount',
 'avg_transaction_amount',
 'total_loan_interest_income',
 'total_card_fee_income',
 'total_other_fee_income',
 'total_deposit_interest_expense',
 'total_service_cost',
 'total_net_revenue']

In [78]:
customer_360["default_flag"].value_counts(dropna=False)

default_flag
0    8500
1    1500
Name: count, dtype: int64

# Calculate overall default rate

In [79]:
overall_default_rate = customer_360["default_flag"].mean() * 100

print(f"Overall Default Rate: {overall_default_rate:.2f}%")

Overall Default Rate: 15.00%

# Default Rate by Credit Score

In [80]:
customer_360["credit_score_band"] = pd.cut(
    customer_360["credit_score"],
    bins=[0, 579, 669, 739, 799, 850],
    labels=[
        "Poor",
        "Fair",
        "Good",
        "Very Good",
        "Exceptional"
    ],
    include_lowest=True
)

In [81]:
credit_score_risk = (
    customer_360
    .groupby("credit_score_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean")
    )
    .reset_index()
)

credit_score_risk["default_rate"] = (
    credit_score_risk["default_rate"] * 100
)

credit_score_risk

  credit_score_band  customers  defaults  default_rate
0              Poor        289       289    100.000000
1              Fair       2487       332     13.349417
2              Good       3897       480     12.317167
3         Very Good       2348       302     12.862010
4       Exceptional        979        97      9.908069

# DTI vs Default Rate

In [82]:
customer_360["dti_band"] = pd.cut(
    customer_360["debt_to_income_pct"],
    bins=[-float("inf"), 20, 35, 50, 100, float("inf")],
    labels=[
        "<=20%",
        "21-35%",
        "36-50%",
        "51-100%",
        ">100%"
    ]
)

In [83]:
dti_risk = (
    customer_360
    .groupby("dti_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean"),
        total_outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

dti_risk["default_rate"] = (
    dti_risk["default_rate"] * 100
)

dti_risk

  dti_band  customers  defaults  default_rate  total_outstanding
0    <=20%       1589       227     14.285714       7.371730e+08
1   21-35%       2801       418     14.923242       1.402412e+09
2   36-50%       3063       476     15.540320       1.422464e+09
3  51-100%       2544       378     14.858491       1.280878e+09
4    >100%          3         1     33.333333       1.618833e+06

# Missed Payments vs Default

In [84]:
customer_360["missed_payment_band"] = pd.cut(
    customer_360["missed_payments_12m"],
    bins=[-1, 0, 1, 2, 4, float("inf")],
    labels=[
        "0",
        "1",
        "2",
        "3-4",
        "5+"
    ]
)

In [85]:
missed_payment_risk = (
    customer_360
    .groupby("missed_payment_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean"),
        total_outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

missed_payment_risk["default_rate"] = (
    missed_payment_risk["default_rate"] * 100
)

missed_payment_risk

  missed_payment_band  customers  defaults  default_rate  total_outstanding
0                   0       4859       707     14.550319       2.467091e+09
1                   1       3529       509     14.423349       1.619535e+09
2                   2       1269       187     14.736013       5.933696e+08
3                 3-4        337        91     27.002967       1.551761e+08
4                  5+          6         6    100.000000       9.374247e+06

# Credit Card Utilization vs Default

In [86]:
customer_360["utilization_band"] = pd.cut(
    customer_360["avg_utilization"],
    bins=[-float("inf"), 30, 50, 70, 90, float("inf")],
    labels=[
        "<=30%",
        "31-50%",
        "51-70%",
        "71-90%",
        ">90%"
    ]
)

In [87]:
utilization_risk = (
    customer_360
    .groupby("utilization_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean"),
        total_outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

utilization_risk["default_rate"] = (
    utilization_risk["default_rate"] * 100
)

utilization_risk

  utilization_band  customers  defaults  default_rate  total_outstanding
0            <=30%       2964       450     15.182186       1.459694e+09
1           31-50%       1685       236     14.005935       7.896832e+08
2           51-70%        384        60     15.625000       1.625122e+08
3           71-90%         24         2      8.333333       1.020623e+07
4             >90%          0         0           NaN       0.000000e+00

# Income Segment vs Default

In [88]:
customer_360["income_band"] = pd.cut(
    customer_360["annual_income"],
    bins=[0, 300000, 600000, 1000000, 2000000, float("inf")],
    labels=[
        "<3L",
        "3-6L",
        "6-10L",
        "10-20L",
        "20L+"
    ],
    include_lowest=True
)

In [89]:
income_risk = (
    customer_360
    .groupby("income_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean"),
        total_outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

income_risk["default_rate"] = (
    income_risk["default_rate"] * 100
)

income_risk

  income_band  customers  defaults  default_rate  total_outstanding
0         <3L       1131       170     15.030946       5.355478e+08
1        3-6L       3302       494     14.960630       1.663526e+09
2       6-10L       3001       439     14.628457       1.464218e+09
3      10-20L       2128       323     15.178571       9.621586e+08
4        20L+        438        74     16.894977       2.190947e+08

In [90]:
customer_360["default_flag"].value_counts(dropna=False)

default_flag
0    8500
1    1500
Name: count, dtype: int64

In [91]:
customer_360.columns.tolist()

['customer_id',
 'customer_name',
 'age',
 'gender',
 'city',
 'occupation',
 'education',
 'annual_income',
 'customer_segment',
 'customer_since',
 'income_band',
 'age_group',
 'credit_score',
 'debt_to_income_pct',
 'missed_payments_12m',
 'delinquency_days',
 'default_flag',
 'risk_band',
 'dti_band',
 'credit_score_band',
 'missed_payment_band',
 'delinquency_band',
 'total_loans',
 'total_loan_amount',
 'total_outstanding',
 'avg_interest_rate',
 'total_cards',
 'total_credit_limit',
 'total_card_balance',
 'avg_utilization',
 'savings_account',
 'current_account',
 'loan',
 'credit_card',
 'insurance',
 'mutual_fund',
 'fixed_deposit',
 'product_count',
 'total_transactions',
 'total_transaction_amount',
 'avg_transaction_amount',
 'total_loan_interest_income',
 'total_card_fee_income',
 'total_other_fee_income',
 'total_deposit_interest_expense',
 'total_service_cost',
 'total_net_revenue',
 'utilization_band']

# Loan Portfolio Risk

In [92]:
loans_clean.columns.tolist()

['loan_id',
 'customer_id',
 'loan_type',
 'loan_amount',
 'outstanding_amount',
 'interest_rate',
 'tenure_months',
 'start_date',
 'loan_status',
 'emi_amount',
 'outstanding_ratio',
 'exposure_band']

In [93]:
loan_risk = loans_clean.merge(
    customer_360[
        [
            "customer_id",
            "default_flag",
            "credit_score",
            "debt_to_income_pct",
            "risk_band"
        ]
    ],
    on="customer_id",
    how="left"
)

loan_risk.head()

,loan_id,customer_id,loan_type,loan_amount,outstanding_amount,interest_rate,tenure_months,start_date,loan_status,emi_amount,outstanding_ratio,exposure_band,default_flag,credit_score,debt_to_income_pct,risk_band
0,LOAN0000001,CUST007490,Home Loan,100000,42858.65,14.08,84,2022-08-01,Closed,2752.99,42.858650,Low Exposure,1,662,2.00,Medium Risk
1,LOAN0000002,CUST006448,Home Loan,750000,594782.69,18.28,84,2024-06-19,Active,13901.01,79.304359,High Exposure,0,725,48.09,Low Risk
2,LOAN0000003,CUST006486,Business Loan,1000000,842017.97,16.13,36,2019-03-19,Default,18592.35,84.201797,High Exposure,0,682,37.20,Low Risk
3,LOAN0000004,CUST006221,Home Loan,500000,310144.21,12.28,240,2025-01-06,Active,10017.62,62.028842,Medium Exposure,0,663,38.37,Medium Risk
4,LOAN0000005,CUST008947,Home Loan,250000,117748.33,8.00,180,2024-10-29,Active,5654.53,47.099332,Medium Exposure,0,734,49.90,Low Risk

# Calculate Loan-Level Exposure

In [94]:
loan_risk["outstanding_pct"] = (
    loan_risk["outstanding_amount"]
    / loan_risk["loan_amount"]
) * 100

In [95]:
loan_risk["defaulted_exposure"] = (
    loan_risk["outstanding_amount"]
    .where(loan_risk["default_flag"] == 1, 0)
)

In [96]:
loan_risk[
    [
        "loan_id",
        "customer_id",
        "loan_type",
        "loan_amount",
        "outstanding_amount",
        "default_flag",
        "defaulted_exposure"
    ]
].head()

,loan_id,customer_id,loan_type,loan_amount,outstanding_amount,default_flag,defaulted_exposure
0,LOAN0000001,CUST007490,Home Loan,100000,42858.65,1,42858.65
1,LOAN0000002,CUST006448,Home Loan,750000,594782.69,0,0.00
2,LOAN0000003,CUST006486,Business Loan,1000000,842017.97,0,0.00
3,LOAN0000004,CUST006221,Home Loan,500000,310144.21,0,0.00
4,LOAN0000005,CUST008947,Home Loan,250000,117748.33,0,0.00

# Loan Type Risk Analysis

In [97]:
loan_type_risk = (
    loan_risk
    .groupby("loan_type")
    .agg(
        loans=("loan_id", "nunique"),
        customers=("customer_id", "nunique"),
        total_loan_amount=("loan_amount", "sum"),
        total_outstanding=("outstanding_amount", "sum"),
        defaults=("default_flag", "sum"),
        defaulted_exposure=("defaulted_exposure", "sum")
    )
    .reset_index()
)

In [98]:
loan_type_risk["default_rate"] = (
    loan_type_risk["defaults"]
    / loan_type_risk["loans"]
) * 100

In [99]:
loan_type_risk["defaulted_exposure_pct"] = (
    loan_type_risk["defaulted_exposure"]
    / loan_type_risk["total_outstanding"]
) * 100

In [100]:
loan_type_risk.sort_values(
    "default_rate",
    ascending=False
)

,loan_type,loans,customers,total_loan_amount,total_outstanding,defaults,defaulted_exposure,default_rate,defaulted_exposure_pct
0,Auto Loan,1167,1099,1679400000,8.529715e+08,181,1.176310e+08,15.509854,13.790733
1,Business Loan,1121,1051,1672350000,8.465164e+08,171,1.119482e+08,15.254237,13.224575
3,Home Loan,1573,1473,2338050000,1.207853e+09,230,1.913077e+08,14.621742,15.838660
4,Personal Loan,2014,1829,2974600000,1.462457e+09,282,2.000506e+08,14.001986,13.679078
2,Education Loan,625,607,918800000,4.747480e+08,75,6.005872e+07,12.000000,12.650652

# Overall Portfolio Exposure

In [101]:
portfolio_summary = pd.DataFrame({
    "Metric": [
        "Total Loans",
        "Total Loan Amount",
        "Total Outstanding",
        "Defaulted Loans",
        "Defaulted Exposure",
        "Overall Default Rate"
    ],
    "Value": [
        loan_risk["loan_id"].nunique(),
        loan_risk["loan_amount"].sum(),
        loan_risk["outstanding_amount"].sum(),
        loan_risk.loc[
            loan_risk["default_flag"] == 1,
            "loan_id"
        ].nunique(),
        loan_risk["defaulted_exposure"].sum(),
        loan_risk["default_flag"].mean() * 100
    ]
})

portfolio_summary

                 Metric         Value
0           Total Loans  6.500000e+03
1     Total Loan Amount  9.583200e+09
2     Total Outstanding  4.844546e+09
3       Defaulted Loans  9.390000e+02
4    Defaulted Exposure  6.809963e+08
5  Overall Default Rate  1.444615e+01

# Risk Band × Loan Exposure

In [102]:
risk_band_loan = (
    loan_risk
    .groupby("risk_band")
    .agg(
        loans=("loan_id", "nunique"),
        customers=("customer_id", "nunique"),
        total_loan_amount=("loan_amount", "sum"),
        total_outstanding=("outstanding_amount", "sum"),
        defaults=("default_flag", "sum"),
        defaulted_exposure=("defaulted_exposure", "sum")
    )
    .reset_index()
)

In [103]:
risk_band_loan["default_rate"] = (
    risk_band_loan["defaults"]
    / risk_band_loan["loans"]
) * 100

In [104]:
risk_band_loan["exposure_at_risk_pct"] = (
    risk_band_loan["defaulted_exposure"]
    / risk_band_loan["total_outstanding"]
) * 100

In [105]:
risk_band_loan

,risk_band,loans,customers,total_loan_amount,total_outstanding,defaults,defaulted_exposure,default_rate,exposure_at_risk_pct
0,High Risk,192,142,281950000,1.405968e+08,192,1.405968e+08,100.000000,100.000000
1,Low Risk,2516,1856,3644400000,1.850420e+09,287,1.892584e+08,11.406995,10.227863
2,Medium Risk,1634,1226,2420050000,1.218141e+09,216,1.573083e+08,13.219094,12.913800
3,Very Low Risk,2158,1594,3236800000,1.635388e+09,244,1.938328e+08,11.306766,11.852405

# One important validation

In [106]:
loan_risk["default_flag"].isna().sum()

np.int64(0)

In [107]:
loan_risk["customer_id"].nunique()

4818

In [109]:
loans_clean["customer_id"].nunique()

4818

# Customer Segment Risk

In [117]:
customer_segment_risk = (
    customer_360
    .groupby("customer_segment")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean"),
        total_outstanding=("total_outstanding", "sum"),
        total_loan_amount=("total_loan_amount", "sum"),
        total_net_revenue=("total_net_revenue", "sum")
    )
    .reset_index()
)

customer_segment_risk["default_rate"] = (
    customer_segment_risk["default_rate"] * 100
)

customer_segment_risk["defaulted_exposure"] = (
    customer_360
    .assign(
        defaulted_exposure=lambda x:
        x["total_outstanding"].where(x["default_flag"] == 1, 0)
    )
    .groupby("customer_segment")["defaulted_exposure"]
    .sum()
    .values
)

customer_segment_risk

,customer_segment,customers,defaults,default_rate,total_outstanding,total_loan_amount,total_net_revenue,defaulted_exposure
0,Affluent,2500,375,15.000000,1.222599e+09,2.437700e+09,5.183145e+07,1.656188e+08
1,High Net Worth,426,67,15.727700,2.122933e+08,4.276500e+08,8.856773e+06,2.797438e+07
2,Mass Market,5738,851,14.830952,2.767404e+09,5.389200e+09,1.213436e+08,3.944929e+08
3,Premium,1336,207,15.494012,6.422489e+08,1.328650e+09,2.774608e+07,9.291015e+07

# Sort by Default Rate

In [118]:
customer_segment_risk.sort_values(
    "default_rate",
    ascending=False
)

,customer_segment,customers,defaults,default_rate,total_outstanding,total_loan_amount,total_net_revenue,defaulted_exposure
1,High Net Worth,426,67,15.727700,2.122933e+08,4.276500e+08,8.856773e+06,2.797438e+07
3,Premium,1336,207,15.494012,6.422489e+08,1.328650e+09,2.774608e+07,9.291015e+07
0,Affluent,2500,375,15.000000,1.222599e+09,2.437700e+09,5.183145e+07,1.656188e+08
2,Mass Market,5738,851,14.830952,2.767404e+09,5.389200e+09,1.213436e+08,3.944929e+08

# City-Level Risk

In [119]:
city_risk = (
    customer_360
    .groupby("city")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean"),
        total_outstanding=("total_outstanding", "sum"),
        total_loan_amount=("total_loan_amount", "sum")
    )
    .reset_index()
)

city_risk["default_rate"] = (
    city_risk["default_rate"] * 100
)

city_risk = city_risk.sort_values(
    "default_rate",
    ascending=False
)

city_risk.head(15)

,city,customers,defaults,default_rate,total_outstanding,total_loan_amount
2,Chennai,1047,183,17.478510,4.604854e+08,9.163500e+08
0,Ahmedabad,969,156,16.099071,5.179545e+08,9.682500e+08
4,Hyderabad,1026,160,15.594542,5.314153e+08,1.037400e+09
1,Bengaluru,1029,157,15.257532,4.518155e+08,9.317000e+08
5,Jaipur,987,149,15.096251,4.526428e+08,9.158500e+08
8,Patna,981,148,15.086646,4.601369e+08,9.194500e+08
6,Kolkata,995,149,14.974874,4.632707e+08,9.275000e+08
9,Pune,1016,149,14.665354,4.762721e+08,1.007200e+09
3,Delhi,971,124,12.770340,5.243365e+08,9.870000e+08
7,Mumbai,979,125,12.768131,5.062159e+08,9.725000e+08

# Occupation Risk

In [120]:
occupation_risk = (
    customer_360
    .groupby("occupation")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean"),
        total_outstanding=("total_outstanding", "sum"),
        total_loan_amount=("total_loan_amount", "sum")
    )
    .reset_index()
)

occupation_risk["default_rate"] = (
    occupation_risk["default_rate"] * 100
)

occupation_risk.sort_values(
    "default_rate",
    ascending=False
)

,occupation,customers,defaults,default_rate,total_outstanding,total_loan_amount
0,Business Owner,1667,266,15.956809,8.085982e+08,1.582350e+09
3,Salaried,4486,685,15.269728,2.191504e+09,4.352950e+09
1,Professional,1219,181,14.848236,6.091103e+08,1.183550e+09
2,Retired,384,56,14.583333,1.627802e+08,3.318000e+08
5,Student,700,99,14.142857,3.276953e+08,6.427000e+08
4,Self-Employed,1544,213,13.795337,7.448574e+08,1.489850e+09

# Age Group Risk

In [121]:
age_group_risk = (
    customer_360
    .groupby("age_group")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean"),
        total_outstanding=("total_outstanding", "sum"),
        total_loan_amount=("total_loan_amount", "sum")
    )
    .reset_index()
)

age_group_risk["default_rate"] = (
    age_group_risk["default_rate"] * 100
)

age_group_risk

,age_group,customers,defaults,default_rate,total_outstanding,total_loan_amount
0,18-24,784,112,14.285714,3.965895e+08,7.890500e+08
1,25-34,1936,293,15.134298,9.717589e+08,1.983150e+09
2,35-44,2059,304,14.764449,9.995511e+08,2.001850e+09
3,45-54,2011,307,15.266037,9.252105e+08,1.792600e+09
4,55-64,1986,292,14.702920,9.776891e+08,1.913350e+09
5,65+,1224,192,15.686275,5.737465e+08,1.103200e+09

# Education Risk

In [122]:
education_risk = (
    customer_360
    .groupby("education")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        default_rate=("default_flag", "mean"),
        total_outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

education_risk["default_rate"] = (
    education_risk["default_rate"] * 100
)

education_risk

      education  customers  defaults  default_rate  total_outstanding
0          10th        647        88     13.601236       3.496485e+08
1          12th       1189       201     16.904962       6.815618e+08
2       Diploma        965       148     15.336788       4.730500e+08
3      Graduate       4808       703     14.621464       2.294146e+09
4  Postgraduate       2391       360     15.056462       1.046139e+09

# The important part: minimum sample-size filter

In [123]:
segment_risk_reliable = customer_segment_risk[
    customer_segment_risk["customers"] >= 100
].sort_values(
    "default_rate",
    ascending=False
)

segment_risk_reliable

,customer_segment,customers,defaults,default_rate,total_outstanding,total_loan_amount,total_net_revenue,defaulted_exposure
1,High Net Worth,426,67,15.727700,2.122933e+08,4.276500e+08,8.856773e+06,2.797438e+07
3,Premium,1336,207,15.494012,6.422489e+08,1.328650e+09,2.774608e+07,9.291015e+07
0,Affluent,2500,375,15.000000,1.222599e+09,2.437700e+09,5.183145e+07,1.656188e+08
2,Mass Market,5738,851,14.830952,2.767404e+09,5.389200e+09,1.213436e+08,3.944929e+08

In [124]:
city_risk_reliable = city_risk[
    city_risk["customers"] >= 100
]

city_risk_reliable.head(15)

,city,customers,defaults,default_rate,total_outstanding,total_loan_amount
2,Chennai,1047,183,17.478510,4.604854e+08,9.163500e+08
0,Ahmedabad,969,156,16.099071,5.179545e+08,9.682500e+08
4,Hyderabad,1026,160,15.594542,5.314153e+08,1.037400e+09
1,Bengaluru,1029,157,15.257532,4.518155e+08,9.317000e+08
5,Jaipur,987,149,15.096251,4.526428e+08,9.158500e+08
8,Patna,981,148,15.086646,4.601369e+08,9.194500e+08
6,Kolkata,995,149,14.974874,4.632707e+08,9.275000e+08
9,Pune,1016,149,14.665354,4.762721e+08,1.007200e+09
3,Delhi,971,124,12.770340,5.243365e+08,9.870000e+08
7,Mumbai,979,125,12.768131,5.062159e+08,9.725000e+08

In [125]:
occupation_risk_reliable = occupation_risk[
    occupation_risk["customers"] >= 100
].sort_values(
    "default_rate",
    ascending=False
)

occupation_risk_reliable

,occupation,customers,defaults,default_rate,total_outstanding,total_loan_amount
0,Business Owner,1667,266,15.956809,8.085982e+08,1.582350e+09
3,Salaried,4486,685,15.269728,2.191504e+09,4.352950e+09
1,Professional,1219,181,14.848236,6.091103e+08,1.183550e+09
2,Retired,384,56,14.583333,1.627802e+08,3.318000e+08
5,Student,700,99,14.142857,3.276953e+08,6.427000e+08
4,Self-Employed,1544,213,13.795337,7.448574e+08,1.489850e+09

# Risk Band × Exposure

In [126]:
risk_concentration = (
    customer_360
    .groupby("risk_band")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        total_outstanding=("total_outstanding", "sum"),
        total_loan_amount=("total_loan_amount", "sum"),
        total_net_revenue=("total_net_revenue", "sum")
    )
    .reset_index()
)

risk_concentration["default_rate"] = (
    risk_concentration["defaults"]
    / risk_concentration["customers"]
) * 100

risk_concentration["defaulted_exposure"] = (
    customer_360
    .assign(
        defaulted_exposure=lambda x:
        x["total_outstanding"].where(
            x["default_flag"] == 1, 0
        )
    )
    .groupby("risk_band")["defaulted_exposure"]
    .sum()
    .values
)

risk_concentration["exposure_at_risk_pct"] = (
    risk_concentration["defaulted_exposure"]
    / risk_concentration["total_outstanding"]
) * 100

risk_concentration

,risk_band,customers,defaults,total_outstanding,total_loan_amount,total_net_revenue,default_rate,defaulted_exposure,exposure_at_risk_pct
0,High Risk,289,289,1.405968e+08,2.819500e+08,5992916.58,100.000000,1.405968e+08,100.000000
1,Low Risk,3897,480,1.850420e+09,3.644400e+09,82566769.33,12.317167,1.892584e+08,10.227863
2,Medium Risk,2487,332,1.218141e+09,2.420050e+09,52223800.26,13.349417,1.573083e+08,12.913800
3,Very Low Risk,3327,399,1.635388e+09,3.236800e+09,68994448.19,11.992786,1.938328e+08,11.852405

# Calculate each risk band's share of total exposure

In [127]:
risk_concentration["exposure_share_pct"] = (
    risk_concentration["total_outstanding"]
    / risk_concentration["total_outstanding"].sum()
) * 100

In [128]:
risk_concentration[
    [
        "risk_band",
        "customers",
        "defaults",
        "default_rate",
        "total_outstanding",
        "defaulted_exposure",
        "exposure_at_risk_pct",
        "exposure_share_pct",
        "total_net_revenue"
    ]
]

,risk_band,customers,defaults,default_rate,total_outstanding,defaulted_exposure,exposure_at_risk_pct,exposure_share_pct,total_net_revenue
0,High Risk,289,289,100.000000,1.405968e+08,1.405968e+08,100.000000,2.902166,5992916.58
1,Low Risk,3897,480,12.317167,1.850420e+09,1.892584e+08,10.227863,38.195941,82566769.33
2,Medium Risk,2487,332,13.349417,1.218141e+09,1.573083e+08,12.913800,25.144586,52223800.26
3,Very Low Risk,3327,399,11.992786,1.635388e+09,1.938328e+08,11.852405,33.757307,68994448.19

# High-Risk Customers and Exposure

In [129]:
high_risk_customers = customer_360[
    customer_360["risk_band"] == "High Risk"
].copy()

In [130]:
high_risk_summary = pd.DataFrame({
    "Metric": [
        "High Risk Customers",
        "High Risk Defaults",
        "High Risk Outstanding",
        "High Risk Loan Amount",
        "High Risk Net Revenue"
    ],
    "Value": [
        high_risk_customers["customer_id"].nunique(),
        high_risk_customers["default_flag"].sum(),
        high_risk_customers["total_outstanding"].sum(),
        high_risk_customers["total_loan_amount"].sum(),
        high_risk_customers["total_net_revenue"].sum()
    ]
})

high_risk_summary

                  Metric         Value
0    High Risk Customers  2.890000e+02
1     High Risk Defaults  2.890000e+02
2  High Risk Outstanding  1.405968e+08
3  High Risk Loan Amount  2.819500e+08
4  High Risk Net Revenue  5.992917e+06

# Identify High Exposure + Historical Default Customers

In [131]:
customer_360["exposure_band"] = pd.cut(
    customer_360["total_outstanding"],
    bins=[
        -float("inf"),
        100000,
        500000,
        1000000,
        2500000,
        float("inf")
    ],
    labels=[
        "<1L",
        "1-5L",
        "5-10L",
        "10-25L",
        "25L+"
    ]
)

In [132]:
exposure_risk = (
    customer_360
    .groupby("exposure_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        total_outstanding=("total_outstanding", "sum"),
        total_net_revenue=("total_net_revenue", "sum")
    )
    .reset_index()
)

exposure_risk["default_rate"] = (
    exposure_risk["defaults"]
    / exposure_risk["customers"]
) * 100

exposure_risk

,exposure_band,customers,defaults,total_outstanding,total_net_revenue,default_rate
0,<1L,726,102,4.017184e+07,14937997.00,14.049587
1,1-5L,1550,225,4.346821e+08,32804214.89,14.516129
2,5-10L,1026,158,7.419152e+08,20789228.64,15.399610
3,10-25L,993,147,1.584733e+09,21829750.27,14.803625
4,25L+,523,73,2.043044e+09,11283017.76,13.957935

# Risk × Exposure Matrix

In [133]:
risk_exposure_matrix = (
    customer_360
    .groupby(
        ["risk_band", "exposure_band"],
        observed=False
    )
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        total_outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

risk_exposure_matrix["default_rate"] = (
    risk_exposure_matrix["defaults"]
    / risk_exposure_matrix["customers"]
) * 100

risk_exposure_matrix

,risk_band,exposure_band,customers,defaults,total_outstanding,default_rate
0,High Risk,<1L,23,23,1.304768e+06,100.000000
1,High Risk,1-5L,46,46,1.332024e+07,100.000000
2,High Risk,5-10L,22,22,1.679296e+07,100.000000
3,High Risk,10-25L,39,39,5.876485e+07,100.000000
4,High Risk,25L+,12,12,5.041394e+07,100.000000
5,Low Risk,<1L,277,30,1.548454e+07,10.830325
6,Low Risk,1-5L,592,69,1.647804e+08,11.655405
7,Low Risk,5-10L,408,59,2.963925e+08,14.460784
8,Low Risk,10-25L,389,38,6.204903e+08,9.768638
9,Low Risk,25L+,190,19,7.532721e+08,10.000000
10,Medium Risk,<1L,190,25,1.035689e+07,13.157895
11,Medium Risk,1-5L,398,49,1.101623e+08,12.311558
12,Medium Risk,5-10L,250,30,1.809861e+08,12.000000
13,Medium Risk,10-25L,257,37,4.156294e+08,14.396887
14,Medium Risk,25L+,131,17,5.010063e+08,12.977099
15,Very Low Risk,<1L,236,24,1.302564e+07,10.169492
16,Very Low Risk,1-5L,514,61,1.464192e+08,11.867704
17,Very Low Risk,5-10L,346,47,2.477436e+08,13.583815
18,Very Low Risk,10-25L,308,33,4.898484e+08,10.714286
19,Very Low Risk,25L+,190,25,7.383513e+08,13.157895

# Find the largest exposure concentrations

In [134]:
risk_exposure_matrix.sort_values(
    "total_outstanding",
    ascending=False
)

,risk_band,exposure_band,customers,defaults,total_outstanding,default_rate
9,Low Risk,25L+,190,19,7.532721e+08,10.000000
19,Very Low Risk,25L+,190,25,7.383513e+08,13.157895
8,Low Risk,10-25L,389,38,6.204903e+08,9.768638
14,Medium Risk,25L+,131,17,5.010063e+08,12.977099
18,Very Low Risk,10-25L,308,33,4.898484e+08,10.714286
13,Medium Risk,10-25L,257,37,4.156294e+08,14.396887
7,Low Risk,5-10L,408,59,2.963925e+08,14.460784
17,Very Low Risk,5-10L,346,47,2.477436e+08,13.583815
12,Medium Risk,5-10L,250,30,1.809861e+08,12.000000
6,Low Risk,1-5L,592,69,1.647804e+08,11.655405
16,Very Low Risk,1-5L,514,61,1.464192e+08,11.867704
11,Medium Risk,1-5L,398,49,1.101623e+08,12.311558
3,High Risk,10-25L,39,39,5.876485e+07,100.000000
4,High Risk,25L+,12,12,5.041394e+07,100.000000
2,High Risk,5-10L,22,22,1.679296e+07,100.000000
5,Low Risk,<1L,277,30,1.548454e+07,10.830325
1,High Risk,1-5L,46,46,1.332024e+07,100.000000
15,Very Low Risk,<1L,236,24,1.302564e+07,10.169492
10,Medium Risk,<1L,190,25,1.035689e+07,13.157895
0,High Risk,<1L,23,23,1.304768e+06,100.000000

# Find the largest exposure concentrations

In [135]:
risk_exposure_matrix.sort_values(
    "defaults",
    ascending=False
)

,risk_band,exposure_band,customers,defaults,total_outstanding,default_rate
6,Low Risk,1-5L,592,69,1.647804e+08,11.655405
16,Very Low Risk,1-5L,514,61,1.464192e+08,11.867704
7,Low Risk,5-10L,408,59,2.963925e+08,14.460784
11,Medium Risk,1-5L,398,49,1.101623e+08,12.311558
17,Very Low Risk,5-10L,346,47,2.477436e+08,13.583815
1,High Risk,1-5L,46,46,1.332024e+07,100.000000
3,High Risk,10-25L,39,39,5.876485e+07,100.000000
8,Low Risk,10-25L,389,38,6.204903e+08,9.768638
13,Medium Risk,10-25L,257,37,4.156294e+08,14.396887
18,Very Low Risk,10-25L,308,33,4.898484e+08,10.714286
5,Low Risk,<1L,277,30,1.548454e+07,10.830325
12,Medium Risk,5-10L,250,30,1.809861e+08,12.000000
10,Medium Risk,<1L,190,25,1.035689e+07,13.157895
19,Very Low Risk,25L+,190,25,7.383513e+08,13.157895
15,Very Low Risk,<1L,236,24,1.302564e+07,10.169492
0,High Risk,<1L,23,23,1.304768e+06,100.000000
2,High Risk,5-10L,22,22,1.679296e+07,100.000000
9,Low Risk,25L+,190,19,7.532721e+08,10.000000
14,Medium Risk,25L+,131,17,5.010063e+08,12.977099
4,High Risk,25L+,12,12,5.041394e+07,100.000000

# Create a management-focused table

In [136]:
risk_management_view = (
    customer_360
    .groupby("risk_band")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        outstanding_exposure=("total_outstanding", "sum"),
        loan_amount=("total_loan_amount", "sum"),
        net_revenue=("total_net_revenue", "sum")
    )
    .reset_index()
)

risk_management_view["default_rate_pct"] = (
    risk_management_view["defaults"]
    / risk_management_view["customers"]
) * 100

risk_management_view["defaulted_exposure"] = (
    customer_360
    .assign(
        defaulted_exposure=lambda x:
        x["total_outstanding"].where(
            x["default_flag"] == 1, 0
        )
    )
    .groupby("risk_band")["defaulted_exposure"]
    .sum()
    .values
)

risk_management_view["exposure_at_risk_pct"] = (
    risk_management_view["defaulted_exposure"]
    / risk_management_view["outstanding_exposure"]
) * 100

risk_management_view

,risk_band,customers,defaults,outstanding_exposure,loan_amount,net_revenue,default_rate_pct,defaulted_exposure,exposure_at_risk_pct
0,High Risk,289,289,1.405968e+08,2.819500e+08,5992916.58,100.000000,1.405968e+08,100.000000
1,Low Risk,3897,480,1.850420e+09,3.644400e+09,82566769.33,12.317167,1.892584e+08,10.227863
2,Medium Risk,2487,332,1.218141e+09,2.420050e+09,52223800.26,13.349417,1.573083e+08,12.913800
3,Very Low Risk,3327,399,1.635388e+09,3.236800e+09,68994448.19,11.992786,1.938328e+08,11.852405

# Risk Band × Revenue

In [137]:
risk_value_analysis = (
    customer_360
    .groupby("risk_band")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        total_outstanding=("total_outstanding", "sum"),
        total_net_revenue=("total_net_revenue", "sum"),
        avg_net_revenue=("total_net_revenue", "mean"),
        total_products=("product_count", "sum")
    )
    .reset_index()
)

risk_value_analysis["default_rate"] = (
    risk_value_analysis["defaults"]
    / risk_value_analysis["customers"]
) * 100

risk_value_analysis["avg_outstanding_per_customer"] = (
    risk_value_analysis["total_outstanding"]
    / risk_value_analysis["customers"]
)

risk_value_analysis["avg_revenue_per_customer"] = (
    risk_value_analysis["total_net_revenue"]
    / risk_value_analysis["customers"]
)

risk_value_analysis

,risk_band,customers,defaults,total_outstanding,total_net_revenue,avg_net_revenue,total_products,default_rate,avg_outstanding_per_customer,avg_revenue_per_customer
0,High Risk,289,289,1.405968e+08,5992916.58,20736.735571,936,100.000000,486493.969031,20736.735571
1,Low Risk,3897,480,1.850420e+09,82566769.33,21252.707678,13155,12.317167,474831.861747,21187.264391
2,Medium Risk,2487,332,1.218141e+09,52223800.26,21024.074179,8446,13.349417,489803.358569,20998.713414
3,Very Low Risk,3327,399,1.635388e+09,68994448.19,20787.721660,11132,11.992786,491550.384112,20737.736156

In [138]:
risk_value_analysis["revenue_share_pct"] = (
    risk_value_analysis["total_net_revenue"]
    / risk_value_analysis["total_net_revenue"].sum()
) * 100

In [139]:
risk_value_analysis[
    [
        "risk_band",
        "customers",
        "defaults",
        "default_rate",
        "total_outstanding",
        "total_net_revenue",
        "revenue_share_pct",
        "avg_revenue_per_customer"
    ]
]

,risk_band,customers,defaults,default_rate,total_outstanding,total_net_revenue,revenue_share_pct,avg_revenue_per_customer
0,High Risk,289,289,100.000000,1.405968e+08,5992916.58,2.856791,20736.735571
1,Low Risk,3897,480,12.317167,1.850420e+09,82566769.33,39.359130,21187.264391
2,Medium Risk,2487,332,13.349417,1.218141e+09,52223800.26,24.894801,20998.713414
3,Very Low Risk,3327,399,11.992786,1.635388e+09,68994448.19,32.889278,20737.736156

# Risk × Revenue Relationship

In [140]:
customer_360["revenue_status"] = customer_360[
    "total_net_revenue"
].apply(
    lambda x: "Positive Revenue"
    if x > 0
    else "Negative/Zero Revenue"
)

In [141]:
risk_revenue_status = (
    customer_360
    .groupby(
        ["risk_band", "revenue_status"]
    )
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        total_outstanding=("total_outstanding", "sum"),
        total_net_revenue=("total_net_revenue", "sum")
    )
    .reset_index()
)

risk_revenue_status["default_rate"] = (
    risk_revenue_status["defaults"]
    / risk_revenue_status["customers"]
) * 100

risk_revenue_status

,risk_band,revenue_status,customers,defaults,total_outstanding,total_net_revenue,default_rate
0,High Risk,Negative/Zero Revenue,17,17,5.470873e+06,-74530.52,100.000000
1,High Risk,Positive Revenue,272,272,1.351259e+08,6067447.10,100.000000
2,Low Risk,Negative/Zero Revenue,176,25,5.094491e+07,-619440.25,14.204545
3,Low Risk,Positive Revenue,3721,455,1.799475e+09,83186209.58,12.227896
4,Medium Risk,Negative/Zero Revenue,138,20,7.187924e+07,-527374.59,14.492754
5,Medium Risk,Positive Revenue,2349,312,1.146262e+09,52751174.85,13.282248
6,Very Low Risk,Negative/Zero Revenue,184,17,6.054437e+07,-679817.88,9.239130
7,Very Low Risk,Positive Revenue,3143,382,1.574844e+09,69674266.07,12.153993

# High Risk × High Exposure × Revenue

In [142]:
customer_360["exposure_level"] = pd.cut(
    customer_360["total_outstanding"],
    bins=[
        -float("inf"),
        500000,
        1000000,
        2500000,
        float("inf")
    ],
    labels=[
        "Low Exposure",
        "Medium Exposure",
        "High Exposure",
        "Very High Exposure"
    ]
)

In [143]:
risk_exposure_value = (
    customer_360
    .groupby(
        ["risk_band", "exposure_level"],
        observed=False
    )
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        outstanding_exposure=("total_outstanding", "sum"),
        net_revenue=("total_net_revenue", "sum")
    )
    .reset_index()
)

risk_exposure_value["default_rate"] = (
    risk_exposure_value["defaults"]
    / risk_exposure_value["customers"]
) * 100

risk_exposure_value

,risk_band,exposure_level,customers,defaults,outstanding_exposure,net_revenue,default_rate
0,High Risk,Low Exposure,69,69,1.462501e+07,1084136.62,100.000000
1,High Risk,Medium Exposure,22,22,1.679296e+07,560500.73,100.000000
2,High Risk,High Exposure,39,39,5.876485e+07,775314.10,100.000000
3,High Risk,Very High Exposure,12,12,5.041394e+07,216225.47,100.000000
4,Low Risk,Low Exposure,869,99,1.802649e+08,18594286.28,11.392405
5,Low Risk,Medium Exposure,408,59,2.963925e+08,7898975.39,14.460784
6,Low Risk,High Exposure,389,38,6.204903e+08,8965627.66,9.768638
7,Low Risk,Very High Exposure,190,19,7.532721e+08,4198541.21,10.000000
8,Medium Risk,Low Exposure,588,74,1.205191e+08,11861090.96,12.585034
9,Medium Risk,Medium Exposure,250,30,1.809861e+08,5236164.25,12.000000
10,Medium Risk,High Exposure,257,37,4.156294e+08,5398828.09,14.396887
11,Medium Risk,Very High Exposure,131,17,5.010063e+08,2870127.51,12.977099
12,Very Low Risk,Low Exposure,750,85,1.594448e+08,16202698.03,11.333333
13,Very Low Risk,Medium Exposure,346,47,2.477436e+08,7093588.27,13.583815
14,Very Low Risk,High Exposure,308,33,4.898484e+08,6689980.42,10.714286
15,Very Low Risk,Very High Exposure,190,25,7.383513e+08,3998123.57,13.157895

# Find the largest historically defaulted exposure

In [144]:
customer_360["defaulted_outstanding"] = (
    customer_360["total_outstanding"]
    .where(
        customer_360["default_flag"] == 1,
        0
    )
)

In [145]:
risk_value_summary = (
    customer_360
    .groupby("risk_band")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        outstanding_exposure=("total_outstanding", "sum"),
        defaulted_exposure=("defaulted_outstanding", "sum"),
        net_revenue=("total_net_revenue", "sum")
    )
    .reset_index()
)

risk_value_summary["default_rate"] = (
    risk_value_summary["defaults"]
    / risk_value_summary["customers"]
) * 100

risk_value_summary["exposure_at_risk_pct"] = (
    risk_value_summary["defaulted_exposure"]
    / risk_value_summary["outstanding_exposure"]
) * 100

risk_value_summary

,risk_band,customers,defaults,outstanding_exposure,defaulted_exposure,net_revenue,default_rate,exposure_at_risk_pct
0,High Risk,289,289,1.405968e+08,1.405968e+08,5992916.58,100.000000,100.000000
1,Low Risk,3897,480,1.850420e+09,1.892584e+08,82566769.33,12.317167,10.227863
2,Medium Risk,2487,332,1.218141e+09,1.573083e+08,52223800.26,13.349417,12.913800
3,Very Low Risk,3327,399,1.635388e+09,1.938328e+08,68994448.19,11.992786,11.852405

# Customer Value by Risk

In [146]:
risk_value_summary["avg_exposure_per_customer"] = (
    risk_value_summary["outstanding_exposure"]
    / risk_value_summary["customers"]
)

risk_value_summary["avg_revenue_per_customer"] = (
    risk_value_summary["net_revenue"]
    / risk_value_summary["customers"]
)

risk_value_summary

,risk_band,customers,defaults,outstanding_exposure,defaulted_exposure,net_revenue,default_rate,exposure_at_risk_pct,avg_exposure_per_customer,avg_revenue_per_customer
0,High Risk,289,289,1.405968e+08,1.405968e+08,5992916.58,100.000000,100.000000,486493.969031,20736.735571
1,Low Risk,3897,480,1.850420e+09,1.892584e+08,82566769.33,12.317167,10.227863,474831.861747,21187.264391
2,Medium Risk,2487,332,1.218141e+09,1.573083e+08,52223800.26,13.349417,12.913800,489803.358569,20998.713414
3,Very Low Risk,3327,399,1.635388e+09,1.938328e+08,68994448.19,11.992786,11.852405,491550.384112,20737.736156

# Create the final risk-analysis table

In [147]:
risk_insight_table = customer_360[
    [
        "customer_id",
        "customer_segment",
        "city",
        "occupation",
        "age_group",
        "annual_income",
        "credit_score",
        "debt_to_income_pct",
        "missed_payments_12m",
        "delinquency_days",
        "avg_utilization",
        "risk_band",
        "default_flag",
        "total_loans",
        "total_loan_amount",
        "total_outstanding",
        "total_cards",
        "total_credit_limit",
        "total_card_balance",
        "product_count",
        "total_net_revenue"
    ]
].copy()

risk_insight_table.head()

,customer_id,customer_segment,city,occupation,age_group,annual_income,credit_score,debt_to_income_pct,missed_payments_12m,delinquency_days,avg_utilization,risk_band,default_flag,total_loans,total_loan_amount,total_outstanding,total_cards,total_credit_limit,total_card_balance,product_count,total_net_revenue
0,CUST000001,Premium,Jaipur,Business Owner,55-64,2453002,841,30.11,1,0,42.920,Very Low Risk,0,1.0,750000.0,408017.88,1.0,500000.0,214600.0,4,6757.69
1,CUST000002,Mass Market,Ahmedabad,Self-Employed,45-54,2052025,703,18.54,1,30,22.680,Low Risk,0,NaN,NaN,NaN,2.0,600000.0,100720.0,4,-6888.28
2,CUST000003,Affluent,Patna,Self-Employed,35-44,492934,813,5.34,0,0,NaN,Very Low Risk,0,NaN,NaN,NaN,NaN,NaN,NaN,4,13831.55
3,CUST000004,Mass Market,Patna,Salaried,55-64,482884,678,5.23,0,30,15.475,Low Risk,0,NaN,NaN,NaN,2.0,1050000.0,95940.0,2,3800.41
4,CUST000005,Mass Market,Kolkata,Professional,25-34,561865,703,65.17,0,0,NaN,Low Risk,0,NaN,NaN,NaN,NaN,NaN,NaN,3,27284.57

# Compare defaulted vs non-defaulted customers

In [148]:
default_comparison = (
    risk_insight_table
    .groupby("default_flag")
    .agg(
        customers=("customer_id", "nunique"),
        avg_income=("annual_income", "mean"),
        avg_credit_score=("credit_score", "mean"),
        avg_dti=("debt_to_income_pct", "mean"),
        avg_missed_payments=("missed_payments_12m", "mean"),
        avg_delinquency=("delinquency_days", "mean"),
        avg_utilization=("avg_utilization", "mean"),
        avg_outstanding=("total_outstanding", "mean"),
        avg_revenue=("total_net_revenue", "mean")
    )
    .reset_index()
)

default_comparison

,default_flag,customers,avg_income,avg_credit_score,avg_dti,avg_missed_payments,avg_delinquency,avg_utilization,avg_outstanding,avg_revenue
0,0,8500,810726.882000,714.256118,37.997689,0.696706,15.607647,28.487170,1.012290e+06,21063.839284
1,1,1500,827879.374667,680.094667,38.113440,0.821333,75.470000,28.414191,9.659521e+05,20812.340836

# Calculate the difference

In [149]:
comparison = default_comparison.set_index("default_flag").T

comparison.columns = [
    "Non_Defaulted",
    "Defaulted"
]

comparison["Difference"] = (
    comparison["Defaulted"]
    - comparison["Non_Defaulted"]
)

comparison

                     Non_Defaulted      Defaulted    Difference
customers             8.500000e+03    1500.000000  -7000.000000
avg_income            8.107269e+05  827879.374667  17152.492667
avg_credit_score      7.142561e+02     680.094667    -34.161451
avg_dti               3.799769e+01      38.113440      0.115751
avg_missed_payments   6.967059e-01       0.821333      0.124627
avg_delinquency       1.560765e+01      75.470000     59.862353
avg_utilization       2.848717e+01      28.414191     -0.072979
avg_outstanding       1.012290e+06  965952.147163 -46337.991235
avg_revenue           2.106384e+04   20812.340836   -251.498448

# Create the final risk-driver summary

In [150]:
credit_score_summary = (
    customer_360
    .groupby("credit_score_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

credit_score_summary["default_rate"] = (
    credit_score_summary["defaults"]
    / credit_score_summary["customers"]
) * 100

credit_score_summary

  credit_score_band  customers  defaults   outstanding  default_rate
0              Poor        289       289  1.405968e+08    100.000000
1              Fair       2487       332  1.218141e+09     13.349417
2              Good       3897       480  1.850420e+09     12.317167
3         Very Good       2348       302  1.130759e+09     12.862010
4       Exceptional        979        97  5.046287e+08      9.908069

# DTI

In [151]:
dti_summary = (
    customer_360
    .groupby("dti_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

dti_summary["default_rate"] = (
    dti_summary["defaults"]
    / dti_summary["customers"]
) * 100

dti_summary

  dti_band  customers  defaults   outstanding  default_rate
0    <=20%       1589       227  7.371730e+08     14.285714
1   21-35%       2801       418  1.402412e+09     14.923242
2   36-50%       3063       476  1.422464e+09     15.540320
3  51-100%       2544       378  1.280878e+09     14.858491
4    >100%          3         1  1.618833e+06     33.333333

# Missed Payments

In [152]:
missed_payment_summary = (
    customer_360
    .groupby("missed_payment_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

missed_payment_summary["default_rate"] = (
    missed_payment_summary["defaults"]
    / missed_payment_summary["customers"]
) * 100

missed_payment_summary

  missed_payment_band  customers  defaults   outstanding  default_rate
0                   0       4859       707  2.467091e+09     14.550319
1                   1       3529       509  1.619535e+09     14.423349
2                   2       1269       187  5.933696e+08     14.736013
3                 3-4        337        91  1.551761e+08     27.002967
4                  5+          6         6  9.374247e+06    100.000000

# Utilization

In [153]:
utilization_summary = (
    customer_360
    .groupby("utilization_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        outstanding=("total_outstanding", "sum")
    )
    .reset_index()
)

utilization_summary["default_rate"] = (
    utilization_summary["defaults"]
    / utilization_summary["customers"]
) * 100

utilization_summary

  utilization_band  customers  defaults   outstanding  default_rate
0            <=30%       2964       450  1.459694e+09     15.182186
1           31-50%       1685       236  7.896832e+08     14.005935
2           51-70%        384        60  1.625122e+08     15.625000
3           71-90%         24         2  1.020623e+07      8.333333
4             >90%          0         0  0.000000e+00           NaN

# Create one final analytical summary

In [154]:
risk_driver_summary = pd.concat(
    [
        credit_score_summary.assign(
            driver="Credit Score",
            segment=credit_score_summary["credit_score_band"].astype(str)
        )[
            [
                "driver",
                "segment",
                "customers",
                "defaults",
                "default_rate",
                "outstanding"
            ]
        ],
        
        dti_summary.assign(
            driver="DTI",
            segment=dti_summary["dti_band"].astype(str)
        )[
            [
                "driver",
                "segment",
                "customers",
                "defaults",
                "default_rate",
                "outstanding"
            ]
        ],
        
        missed_payment_summary.assign(
            driver="Missed Payments",
            segment=missed_payment_summary[
                "missed_payment_band"
            ].astype(str)
        )[
            [
                "driver",
                "segment",
                "customers",
                "defaults",
                "default_rate",
                "outstanding"
            ]
        ],
        
        utilization_summary.assign(
            driver="Credit Utilization",
            segment=utilization_summary[
                "utilization_band"
            ].astype(str)
        )[
            [
                "driver",
                "segment",
                "customers",
                "defaults",
                "default_rate",
                "outstanding"
            ]
        ]
    ],
    ignore_index=True
)

risk_driver_summary

,driver,segment,customers,defaults,default_rate,outstanding
0,Credit Score,Poor,289,289,100.000000,1.405968e+08
1,Credit Score,Fair,2487,332,13.349417,1.218141e+09
2,Credit Score,Good,3897,480,12.317167,1.850420e+09
3,Credit Score,Very Good,2348,302,12.862010,1.130759e+09
4,Credit Score,Exceptional,979,97,9.908069,5.046287e+08
5,DTI,<=20%,1589,227,14.285714,7.371730e+08
6,DTI,21-35%,2801,418,14.923242,1.402412e+09
7,DTI,36-50%,3063,476,15.540320,1.422464e+09
8,DTI,51-100%,2544,378,14.858491,1.280878e+09
9,DTI,>100%,3,1,33.333333,1.618833e+06
10,Missed Payments,0,4859,707,14.550319,2.467091e+09
11,Missed Payments,1,3529,509,14.423349,1.619535e+09
12,Missed Payments,2,1269,187,14.736013,5.933696e+08
13,Missed Payments,3-4,337,91,27.002967,1.551761e+08
14,Missed Payments,5+,6,6,100.000000,9.374247e+06
15,Credit Utilization,<=30%,2964,450,15.182186,1.459694e+09
16,Credit Utilization,31-50%,1685,236,14.005935,7.896832e+08
17,Credit Utilization,51-70%,384,60,15.625000,1.625122e+08
18,Credit Utilization,71-90%,24,2,8.333333,1.020623e+07
19,Credit Utilization,>90%,0,0,NaN,0.000000e+00

# Find the largest exposure associated with defaults

In [158]:
defaulted = customer_360.loc[
    customer_360["default_flag"] == 1
].copy()

default_exposure_summary = pd.DataFrame({
    "value": [
        defaulted["customer_id"].nunique(),
        defaulted["total_outstanding"].sum(),
        defaulted["total_loan_amount"].sum(),
        defaulted["total_net_revenue"].sum()
    ]
}, index=[
    "defaulted_customers",
    "defaulted_outstanding",
    "defaulted_loan_amount",
    "defaulted_revenue"
])

default_exposure_summary

                              value
defaulted_customers    1.500000e+03
defaulted_outstanding  6.809963e+08
defaulted_loan_amount  1.393950e+09
defaulted_revenue      3.111445e+07

# Who is likely to default?

In [160]:
import pandas as pd

# 1. Defaulted vs non-defaulted customer comparison
customer_comparison = (
    customer_360.groupby("default_flag")
    .agg(
        customers=("customer_id", "nunique"),
        avg_credit_score=("credit_score", "mean"),
        avg_dti=("debt_to_income_pct", "mean"),
        avg_missed_payments=("missed_payments_12m", "mean"),
        avg_delinquency_days=("delinquency_days", "mean"),
        avg_utilization=("avg_utilization", "mean"),
        avg_outstanding=("total_outstanding", "mean")
    )
    .round(2)
)

print(customer_comparison)

# 2. Customers with highest observed risk indicators
risky_customers = (
    customer_360.sort_values(
        ["risk_band", "delinquency_days", "credit_score"],
        ascending=[True, False, True]
    )
    .loc[:, [
        "customer_id", "customer_segment", "risk_band",
        "credit_score", "debt_to_income_pct",
        "missed_payments_12m", "delinquency_days",
        "total_outstanding", "default_flag"
    ]]
)

display(risky_customers.head(20))

              customers  avg_credit_score  avg_dti  avg_missed_payments  \
default_flag
0                  8500            714.26    38.00                 0.70
1                  1500            680.09    38.11                 0.82

              avg_delinquency_days  avg_utilization  avg_outstanding
default_flag
0                            15.61            28.49       1012290.14
1                            75.47            28.41        965952.15

,customer_id,customer_segment,risk_band,credit_score,debt_to_income_pct,missed_payments_12m,delinquency_days,total_outstanding,default_flag
2842,CUST002843,High Net Worth,High Risk,472,40.64,0,90,78862.58,1
4955,CUST004956,Mass Market,High Risk,516,50.09,0,90,NaN,1
7298,CUST007299,Mass Market,High Risk,535,9.89,0,90,43241.43,1
5544,CUST005545,Mass Market,High Risk,536,70.65,0,90,NaN,1
9729,CUST009730,Mass Market,High Risk,538,60.65,3,90,342666.56,1
5682,CUST005683,Mass Market,High Risk,539,19.41,0,90,451099.46,1
6217,CUST006218,Affluent,High Risk,541,48.40,0,90,467367.30,1
1762,CUST001763,Premium,High Risk,545,58.97,0,90,687063.98,1
5526,CUST005527,Mass Market,High Risk,546,41.41,1,90,611773.09,1
9462,CUST009463,Mass Market,High Risk,549,35.88,0,90,1265743.18,1
2755,CUST002756,Affluent,High Risk,550,26.80,1,90,NaN,1
1720,CUST001721,Mass Market,High Risk,552,22.57,1,90,NaN,1
8393,CUST008394,Mass Market,High Risk,552,42.18,0,90,108532.99,1
9531,CUST009532,Premium,High Risk,560,41.76,1,90,267833.42,1
6115,CUST006116,Affluent,High Risk,562,30.65,0,90,NaN,1
6066,CUST006067,Mass Market,High Risk,563,50.00,1,90,448844.31,1
3387,CUST003388,Mass Market,High Risk,564,34.55,1,90,NaN,1
3952,CUST003953,Mass Market,High Risk,564,50.61,3,90,37954.77,1
894,CUST000895,Affluent,High Risk,565,2.68,2,90,358590.05,1
956,CUST000957,Premium,High Risk,565,61.00,1,90,NaN,1

# Why is the customer risky?

In [161]:
# Default rate by credit score
credit_score_risk = (
    customer_360.groupby("credit_score_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        exposure=("total_outstanding", "sum")
    )
    .reset_index()
)

credit_score_risk["default_rate_pct"] = (
    credit_score_risk["defaults"] /
    credit_score_risk["customers"] * 100
)

display(credit_score_risk)

# Default rate by delinquency / missed payments
for col in ["missed_payment_band", "delinquency_band"]:
    if col in customer_360.columns:
        result = (
            customer_360.groupby(col, observed=False)
            .agg(
                customers=("customer_id", "nunique"),
                defaults=("default_flag", "sum"),
                exposure=("total_outstanding", "sum")
            )
            .reset_index()
        )
        result["default_rate_pct"] = (
            result["defaults"] / result["customers"] * 100
        )
        print(f"\n{col}")
        display(result)

  credit_score_band  customers  defaults      exposure  default_rate_pct
0              Poor        289       289  1.405968e+08        100.000000
1              Fair       2487       332  1.218141e+09         13.349417
2              Good       3897       480  1.850420e+09         12.317167
3         Very Good       2348       302  1.130759e+09         12.862010
4       Exceptional        979        97  5.046287e+08          9.908069

missed_payment_band

  missed_payment_band  customers  defaults      exposure  default_rate_pct
0                   0       4859       707  2.467091e+09         14.550319
1                   1       3529       509  1.619535e+09         14.423349
2                   2       1269       187  5.933696e+08         14.736013
3                 3-4        337        91  1.551761e+08         27.002967
4                  5+          6         6  9.374247e+06        100.000000

delinquency_band

  delinquency_band  customers  defaults      exposure  default_rate_pct
0        1-30 Days       3821       128  1.822650e+09          3.349908
1       31-60 Days       1232        43  6.250287e+08          3.490260
2       61-90 Days       1206      1206  5.330098e+08        100.000000
3   No Delinquency       3741       123  1.863857e+09          3.287891

# Which customer/loan segments have the highest default rate?

In [162]:
# Customer / loan segment default-rate analysis
segment_cols = [
    "customer_segment",
    "risk_band",
    "credit_score_band",
    "exposure_band"
]

for col in segment_cols:
    if col not in customer_360.columns:
        continue

    segment_result = (
        customer_360.groupby(col, observed=False)
        .agg(
            customers=("customer_id", "nunique"),
            defaults=("default_flag", "sum"),
            total_outstanding=("total_outstanding", "sum"),
            defaulted_exposure=("defaulted_outstanding", "sum")
        )
        .reset_index()
    )

    segment_result["default_rate_pct"] = (
        segment_result["defaults"] /
        segment_result["customers"] * 100
    )

    segment_result["exposure_at_risk_pct"] = (
        segment_result["defaulted_exposure"] /
        segment_result["total_outstanding"] * 100
    )

    segment_result = segment_result.sort_values(
        "default_rate_pct", ascending=False
    )

    print(f"\n{col}")
    display(segment_result)

customer_segment

,customer_segment,customers,defaults,total_outstanding,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
1,High Net Worth,426,67,2.122933e+08,2.797438e+07,15.727700,13.177231
3,Premium,1336,207,6.422489e+08,9.291015e+07,15.494012,14.466378
0,Affluent,2500,375,1.222599e+09,1.656188e+08,15.000000,13.546451
2,Mass Market,5738,851,2.767404e+09,3.944929e+08,14.830952,14.254981

risk_band

,risk_band,customers,defaults,total_outstanding,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
0,High Risk,289,289,1.405968e+08,1.405968e+08,100.000000,100.000000
2,Medium Risk,2487,332,1.218141e+09,1.573083e+08,13.349417,12.913800
1,Low Risk,3897,480,1.850420e+09,1.892584e+08,12.317167,10.227863
3,Very Low Risk,3327,399,1.635388e+09,1.938328e+08,11.992786,11.852405

credit_score_band

,credit_score_band,customers,defaults,total_outstanding,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
0,Poor,289,289,1.405968e+08,1.405968e+08,100.000000,100.000000
1,Fair,2487,332,1.218141e+09,1.573083e+08,13.349417,12.913800
3,Very Good,2348,302,1.130759e+09,1.567725e+08,12.862010,13.864352
2,Good,3897,480,1.850420e+09,1.892584e+08,12.317167,10.227863
4,Exceptional,979,97,5.046287e+08,3.706037e+07,9.908069,7.344087

exposure_band

,exposure_band,customers,defaults,total_outstanding,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
2,5-10L,1026,158,7.419152e+08,1.165694e+08,15.399610,15.711961
3,10-25L,993,147,1.584733e+09,2.259191e+08,14.803625,14.255973
1,1-5L,1550,225,4.346821e+08,6.361815e+07,14.516129,14.635558
0,<1L,726,102,4.017184e+07,6.142632e+06,14.049587,15.290891
4,25L+,523,73,2.043044e+09,2.687470e+08,13.957935,13.154245

# How much exposure is at risk?

In [163]:
# Overall exposure at risk
total_exposure = customer_360["total_outstanding"].sum()

defaulted_exposure = customer_360.loc[
    customer_360["default_flag"] == 1,
    "total_outstanding"
].sum()

exposure_at_risk_pct = (
    defaulted_exposure / total_exposure * 100
)

print(f"Total exposure: ₹{total_exposure:,.2f}")
print(f"Defaulted exposure: ₹{defaulted_exposure:,.2f}")
print(f"Exposure at risk: {exposure_at_risk_pct:.2f}%")

# Segment-wise exposure
exposure_by_risk = (
    customer_360.groupby("risk_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        total_exposure=("total_outstanding", "sum"),
        defaulted_exposure=("defaulted_outstanding", "sum")
    )
    .reset_index()
)

exposure_by_risk["exposure_at_risk_pct"] = (
    exposure_by_risk["defaulted_exposure"] /
    exposure_by_risk["total_exposure"] * 100
)

display(exposure_by_risk)

Total exposure: ₹4,844,545,602.98
Defaulted exposure: ₹680,996,263.75
Exposure at risk: 14.06%

,risk_band,customers,total_exposure,defaulted_exposure,exposure_at_risk_pct
0,High Risk,289,1.405968e+08,1.405968e+08,100.000000
1,Low Risk,3897,1.850420e+09,1.892584e+08,10.227863
2,Medium Risk,2487,1.218141e+09,1.573083e+08,12.913800
3,Very Low Risk,3327,1.635388e+09,1.938328e+08,11.852405

# What patterns can help the bank reduce future credit losses?

In [165]:
default_rate = (
    customer_360.groupby("risk_band")
    .agg(
        customers=("customer_id", "nunique"),
        defaults=("default_flag", "sum"),
        exposure=("total_outstanding", "sum"),
        defaulted_exposure=("defaulted_outstanding", "sum")
    )
    .reset_index()
)

default_rate["default_rate_pct"] = (
    default_rate["defaults"] /
    default_rate["customers"] * 100
)

default_rate["exposure_at_risk_pct"] = (
    default_rate["defaulted_exposure"] /
    default_rate["exposure"] * 100
)

display(default_rate)

,risk_band,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
0,High Risk,289,289,1.405968e+08,1.405968e+08,100.000000,100.000000
1,Low Risk,3897,480,1.850420e+09,1.892584e+08,12.317167,10.227863
2,Medium Risk,2487,332,1.218141e+09,1.573083e+08,13.349417,12.913800
3,Very Low Risk,3327,399,1.635388e+09,1.938328e+08,11.992786,11.852405

In [166]:
features = [
    "credit_score_band",
    "missed_payment_band",
    "delinquency_band",
    "exposure_band",
    "customer_segment"
]

for feature in features:

    result = (
        customer_360.groupby(feature, observed=False)
        .agg(
            customers=("customer_id", "nunique"),
            defaults=("default_flag", "sum"),
            exposure=("total_outstanding", "sum"),
            defaulted_exposure=("defaulted_outstanding", "sum")
        )
        .reset_index()
    )

    result["default_rate_pct"] = (
        result["defaults"] / result["customers"] * 100
    )

    result["exposure_at_risk_pct"] = (
        result["defaulted_exposure"] /
        result["exposure"] * 100
    )

    print("\n", "="*60)
    print(feature)
    display(result.sort_values(
        "default_rate_pct",
        ascending=False
    ))

 ============================================================
credit_score_band

,credit_score_band,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
0,Poor,289,289,1.405968e+08,1.405968e+08,100.000000,100.000000
1,Fair,2487,332,1.218141e+09,1.573083e+08,13.349417,12.913800
3,Very Good,2348,302,1.130759e+09,1.567725e+08,12.862010,13.864352
2,Good,3897,480,1.850420e+09,1.892584e+08,12.317167,10.227863
4,Exceptional,979,97,5.046287e+08,3.706037e+07,9.908069,7.344087

 ============================================================
missed_payment_band

,missed_payment_band,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
4,5+,6,6,9.374247e+06,9.374247e+06,100.000000,100.000000
3,3-4,337,91,1.551761e+08,3.781829e+07,27.002967,24.371204
2,2,1269,187,5.933696e+08,8.510332e+07,14.736013,14.342380
0,0,4859,707,2.467091e+09,3.338837e+08,14.550319,13.533497
1,1,3529,509,1.619535e+09,2.148167e+08,14.423349,13.264102

 ============================================================
delinquency_band

,delinquency_band,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
2,61-90 Days,1206,1206,5.330098e+08,5.330098e+08,100.000000,100.000000
1,31-60 Days,1232,43,6.250287e+08,1.835812e+07,3.490260,2.937165
0,1-30 Days,3821,128,1.822650e+09,7.343102e+07,3.349908,4.028806
3,No Delinquency,3741,123,1.863857e+09,5.619729e+07,3.287891,3.015107

 ============================================================
exposure_band

,exposure_band,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
2,5-10L,1026,158,7.419152e+08,1.165694e+08,15.399610,15.711961
3,10-25L,993,147,1.584733e+09,2.259191e+08,14.803625,14.255973
1,1-5L,1550,225,4.346821e+08,6.361815e+07,14.516129,14.635558
0,<1L,726,102,4.017184e+07,6.142632e+06,14.049587,15.290891
4,25L+,523,73,2.043044e+09,2.687470e+08,13.957935,13.154245

 ============================================================
customer_segment

,customer_segment,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
1,High Net Worth,426,67,2.122933e+08,2.797438e+07,15.727700,13.177231
3,Premium,1336,207,6.422489e+08,9.291015e+07,15.494012,14.466378
0,Affluent,2500,375,1.222599e+09,1.656188e+08,15.000000,13.546451
2,Mass Market,5738,851,2.767404e+09,3.944929e+08,14.830952,14.254981

In [167]:
features = [
    "credit_score_band",
    "missed_payment_band",
    "delinquency_band",
    "exposure_band",
    "customer_segment"
]

for feature in features:

    result = (
        customer_360.groupby(feature, observed=False)
        .agg(
            customers=("customer_id", "nunique"),
            defaults=("default_flag", "sum"),
            exposure=("total_outstanding", "sum"),
            defaulted_exposure=("defaulted_outstanding", "sum")
        )
        .reset_index()
    )

    result["default_rate_pct"] = (
        result["defaults"] / result["customers"] * 100
    )

    result["exposure_at_risk_pct"] = (
        result["defaulted_exposure"] /
        result["exposure"] * 100
    )

    print("\n", "="*60)
    print(feature)
    display(result.sort_values(
        "default_rate_pct",
        ascending=False
    ))

 ============================================================
credit_score_band

,credit_score_band,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
0,Poor,289,289,1.405968e+08,1.405968e+08,100.000000,100.000000
1,Fair,2487,332,1.218141e+09,1.573083e+08,13.349417,12.913800
3,Very Good,2348,302,1.130759e+09,1.567725e+08,12.862010,13.864352
2,Good,3897,480,1.850420e+09,1.892584e+08,12.317167,10.227863
4,Exceptional,979,97,5.046287e+08,3.706037e+07,9.908069,7.344087

 ============================================================
missed_payment_band

,missed_payment_band,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
4,5+,6,6,9.374247e+06,9.374247e+06,100.000000,100.000000
3,3-4,337,91,1.551761e+08,3.781829e+07,27.002967,24.371204
2,2,1269,187,5.933696e+08,8.510332e+07,14.736013,14.342380
0,0,4859,707,2.467091e+09,3.338837e+08,14.550319,13.533497
1,1,3529,509,1.619535e+09,2.148167e+08,14.423349,13.264102

 ============================================================
delinquency_band

,delinquency_band,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
2,61-90 Days,1206,1206,5.330098e+08,5.330098e+08,100.000000,100.000000
1,31-60 Days,1232,43,6.250287e+08,1.835812e+07,3.490260,2.937165
0,1-30 Days,3821,128,1.822650e+09,7.343102e+07,3.349908,4.028806
3,No Delinquency,3741,123,1.863857e+09,5.619729e+07,3.287891,3.015107

 ============================================================
exposure_band

,exposure_band,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
2,5-10L,1026,158,7.419152e+08,1.165694e+08,15.399610,15.711961
3,10-25L,993,147,1.584733e+09,2.259191e+08,14.803625,14.255973
1,1-5L,1550,225,4.346821e+08,6.361815e+07,14.516129,14.635558
0,<1L,726,102,4.017184e+07,6.142632e+06,14.049587,15.290891
4,25L+,523,73,2.043044e+09,2.687470e+08,13.957935,13.154245

 ============================================================
customer_segment

,customer_segment,customers,defaults,exposure,defaulted_exposure,default_rate_pct,exposure_at_risk_pct
1,High Net Worth,426,67,2.122933e+08,2.797438e+07,15.727700,13.177231
3,Premium,1336,207,6.422489e+08,9.291015e+07,15.494012,14.466378
0,Affluent,2500,375,1.222599e+09,1.656188e+08,15.000000,13.546451
2,Mass Market,5738,851,2.767404e+09,3.944929e+08,14.830952,14.254981

# save clean and analysized File

In [168]:
import pandas as pd

output_file = r"C:\Users\abida\OneDrive\Pictures\Banking_Credit_Risk_Analysis_Final.xlsx"

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    # =========================
    # CLEANED / MASTER TABLES
    # =========================

    customers_clean.to_excel(
        writer,
        sheet_name="customers_clean",
        index=False
    )

    defaults_credit_risk_clean.to_excel(
        writer,
        sheet_name="defaults_clean",
        index=False
    )

    loans_clean.to_excel(
        writer,
        sheet_name="loans_clean",
        index=False
    )

    credit_cards_clean.to_excel(
        writer,
        sheet_name="cards_clean",
        index=False
    )

    accounts_deposits_clean.to_excel(
        writer,
        sheet_name="accounts_clean",
        index=False
    )

    transactions_clean.to_excel(
        writer,
        sheet_name="transactions_clean",
        index=False
    )

    interest_revenue_clean.to_excel(
        writer,
        sheet_name="revenue_clean",
        index=False
    )

    product_ownership_clean.to_excel(
        writer,
        sheet_name="products_clean",
        index=False
    )

    # =========================
    # CUSTOMER 360
    # =========================

    customer_360.to_excel(
        writer,
        sheet_name="customer_360",
        index=False
    )

    # =========================
    # ANALYSIS TABLES
    # =========================

    credit_score_summary.to_excel(
        writer,
        sheet_name="risk_credit_score",
        index=False
    )

    dti_summary.to_excel(
        writer,
        sheet_name="risk_dti",
        index=False
    )

    missed_payment_summary.to_excel(
        writer,
        sheet_name="risk_missed_payment",
        index=False
    )

    utilization_summary.to_excel(
        writer,
        sheet_name="risk_utilization",
        index=False
    )

    loan_type_risk.to_excel(
        writer,
        sheet_name="loan_type_risk",
        index=False
    )

    risk_concentration.to_excel(
        writer,
        sheet_name="risk_concentration",
        index=False
    )

    customer_segment_risk.to_excel(
        writer,
        sheet_name="segment_risk",
        index=False
    )

    city_risk.to_excel(
        writer,
        sheet_name="city_risk",
        index=False
    )

    occupation_risk.to_excel(
        writer,
        sheet_name="occupation_risk",
        index=False
    )

    risk_value_analysis.to_excel(
        writer,
        sheet_name="risk_customer_value",
        index=False
    )

    default_comparison.to_excel(
        writer,
        sheet_name="default_comparison",
        index=False
    )

    risk_driver_summary.to_excel(
        writer,
        sheet_name="risk_driver_summary",
        index=False
    )

    default_exposure_summary.to_excel(
        writer,
        sheet_name="default_exposure",
        index=False
    )

print(f"File saved successfully: {output_file}")

File saved successfully: C:\Users\abida\OneDrive\Pictures\Banking_Credit_Risk_Analysis_Final.xlsx